// Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/boBing/addCount": {
            "get": {
                "tags": [
                    "博饼"
                ],
                "summary": "转发阅读推文增加次数",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "token",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/types.ResponseData"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/types.ResponseData"
                        }
                    }
                }
            }
        },
        "/boBing/dayRank": {
            "get": {
                "tags": [
                    "博饼"
                ],
                "summary": "获取博饼日榜（可轮询）",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "token",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/types.ResponseData"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/types.ResponseData"
                        }
                    }
                }
            }
        },
        "/boBing/getCount": {
            "get": {
                "tags": [
                    "博饼"
                ],
                "summary": "博饼获取当天剩余次数",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "token",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/types.ResponseData"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/types.ResponseData"
                        }
                    }
                }
            }
        },
        "/boBing/init": {
            "get": {
                "tags": [
                    "博饼"
                ],
                "summary": "博饼每次进入后的初始化操作",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "token",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/types.ResponseData"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/types.ResponseData"
                        }
                    }
                }
            }
        },
        "/boBing/key": {
            "get": {
                "tags": [
                    "博饼"
                ],
                "summary": "获取密钥",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "token",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/types.ResponseData"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/types.ResponseData"
                        }
                    }
                }
            }
        },
        "/boBing/publish": {
            "post": {
                "tags": [
                    "博饼"
                ],
                "summary": "提交博饼信息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "获取积分及校验,如果是稀有会返回密文，进行广播的校验",
                        "name": "scoreMessage",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/types.ScoreMessage"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/types.ResponseData"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/types.ResponseData"
                        }
                    }
                }
            }
        },
        "/boBing/record": {
            "get": {
                "tags": [
                    "博饼"
                ],
                "summary": "查看自己的博饼记录",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "token",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/types.ResponseData"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/types.ResponseData"
                        }
                    }
                }
            }
        },
        "/boBing/tianXuan": {
            "get": {
                "tags": [
                    "博饼"
                ],
                "summary": "博饼天选榜(可轮询)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "token",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/types.ResponseData"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/types.ResponseData"
                        }
                    }
                }
            }
        },
        "/boBing/top": {
            "get": {
                "tags": [
                    "博饼"
                ],
                "summary": "获取前十及自己的信息（可轮询）",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "token",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/types.ResponseData"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/types.ResponseData"
                        }
                    }
                }
            }
        },
        "/school/gpa": {
            "get": {
                "tags": [
                    "学校"
                ],
                "summary": "绩点",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "token",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/types.ResponseData"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/types.ResponseData"
                        }
                    }
                }
            }
        },
        "/school/grade": {
            "get": {
                "tags": [
                    "学校"
                ],
                "summary": "成绩",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "token",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/types.ResponseData"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/types.ResponseData"
                        }
                    }
                }
            }
        },
        "/school/schedule": {
            "post": {
                "tags": [
                    "学校"
                ],
                "summary": "课表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "获取学期。举例格式：2023-2024-1",
                        "name": "scoreMessage",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/types.SemesterInfo"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/types.ResponseData"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/types.ResponseData"
                        }
                    }
                }
            }
        },
        "/school/xuefen": {
            "get": {
                "tags": [
                    "学校"
                ],
                "summary": "学分",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "token",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/types.ResponseData"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/types.ResponseData"
                        }
                    }
                }
            }
        },
        "/user/bill_login": {
            "post": {
                "tags": [
                    "用户"
                ],
                "summary": "年度账单用户登陆",
                "parameters": [
                    {
                        "description": "微信获取code",
                        "name": "codeInfo",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/types.CodeInfo"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/types.ResponseData"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/types.ResponseData"
                        }
                    }
                }
            }
        },
        "/user/jssdk": {
            "post": {
                "tags": [
                    "用户"
                ],
                "summary": "JS-SDk权限验证配置",
                "parameters": [
                    {
                        "description": "获取url",
                        "name": "codeInfo",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/types.UrlInfo"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/types.ResponseData"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/types.ResponseData"
                        }
                    }
                }
            }
        },
        "/user/login": {
            "post": {
                "tags": [
                    "用户"
                ],
                "summary": "用户登陆",
                "parameters": [
                    {
                        "description": "微信获取code",
                        "name": "codeInfo",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/types.CodeInfo"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/types.ResponseData"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/types.ResponseData"
                        }
                    }
                }
            }
        },
        "/user/school_login": {
            "post": {
                "tags": [
                    "用户"
                ],
                "summary": "校内服务用户登陆",
                "parameters": [
                    {
                        "description": "微信获取code",
                        "name": "codeInfo",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/types.CodeInfo"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/types.ResponseData"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/types.ResponseData"
                        }
                    }
                }
            }
        },
        "/ws/broadcast": {
            "get": {
                "description": "Echoes messages sent from the client back to the client",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "博饼"
                ],
                "summary": "广播信息（使用websocket）",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "获取要广播的内容和token，当提交稀有的博饼记录时，返回密文用于这里进行一个校验",
                        "name": "broadcastMessage",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/types.BroadcastMessage"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/yearBill/appraise": {
            "post": {
                "tags": [
                    "年度账单"
                ],
                "summary": "对年度账单活动进行评价",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "获取积分及校验,如果是稀有会返回密文，进行广播的校验",
                        "name": "scoreMessage",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/types.Appraise"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/types.ResponseData"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/types.ResponseData"
                        }
                    }
                }
            }
        },
        "/yearBill/init": {
            "get": {
                "description": "Echoes messages sent from the client back to the client",
                "tags": [
                    "年度账单"
                ],
                "summary": "数据初始化(websocket)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "token",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/types.ResponseData"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/types.ResponseData"
                        }
                    }
                }
            }
        },
        "/yearBill/learn": {
            "get": {
                "tags": [
                    "年度账单"
                ],
                "summary": "获得学习数据",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "token",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/types.ResponseData"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/types.ResponseData"
                        }
                    }
                }
            }
        },
        "/yearBill/pay": {
            "get": {
                "tags": [
                    "年度账单"
                ],
                "summary": "获得花费数据",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "token",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/types.ResponseData"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/types.ResponseData"
                        }
                    }
                }
            }
        },
        "/yearBill/rank": {
            "get": {
                "tags": [
                    "年度账单"
                ],
                "summary": "获得这是第几份年度账单数据",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "token",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/types.ResponseData"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/types.ResponseData"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "types.Appraise": {
            "type": "object",
            "properties": {
                "appraisal": {
                    "type": "integer"
                }
            }
        },
        "types.BroadcastMessage": {
            "type": "object",
            "properties": {
                "ciphertext": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "token": {
                    "type": "string"
                }
            }
        },
        "types.CodeInfo": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "code",
                    "type": "string"
                }
            }
        },
        "types.ResCode": {
            "type": "integer",
            "enum": [
                1000,
                1001,
                1002
            ],
            "x-enum-varnames": [
                "CodeSuccess",
                "CodeServerBusy",
                "CodeInvalidParam"
            ]
        },
        "types.ResponseData": {
            "type": "object",
            "properties": {
                "code": {
                    "$ref": "#/definitions/types.ResCode"
                },
                "data": {
                    "description": "空的话就不解析了"
                },
                "msg": {}
            }
        },
        "types.ScoreMessage": {
            "type": "object",
            "properties": {
                "detail": {
                    "type": "string"
                },
                "points": {
                    "type": "string"
                }
            }
        },
        "types.SemesterInfo": {
            "type": "object",
            "properties": {
                "semester": {
                    "type": "string"
                }
            }
        },
        "types.UrlInfo": {
            "type": "object",
            "properties": {
                "url": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
