// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v4.23.2
// source: boBing.proto

package boBing

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BoBingPingResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *BoBingPingResponse) Reset() {
	*x = BoBingPingResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_boBing_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BoBingPingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BoBingPingResponse) ProtoMessage() {}

func (x *BoBingPingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_boBing_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BoBingPingResponse.ProtoReflect.Descriptor instead.
func (*BoBingPingResponse) Descriptor() ([]byte, []int) {
	return file_boBing_proto_rawDescGZIP(), []int{0}
}

func (x *BoBingPingResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type BoBingInitRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StuNum   string `protobuf:"bytes,1,opt,name=stuNum,proto3" json:"stuNum,omitempty"`
	NickName string `protobuf:"bytes,2,opt,name=nickName,proto3" json:"nickName,omitempty"`
	OpenId   string `protobuf:"bytes,3,opt,name=openId,proto3" json:"openId,omitempty"`
}

func (x *BoBingInitRequest) Reset() {
	*x = BoBingInitRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_boBing_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BoBingInitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BoBingInitRequest) ProtoMessage() {}

func (x *BoBingInitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_boBing_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BoBingInitRequest.ProtoReflect.Descriptor instead.
func (*BoBingInitRequest) Descriptor() ([]byte, []int) {
	return file_boBing_proto_rawDescGZIP(), []int{1}
}

func (x *BoBingInitRequest) GetStuNum() string {
	if x != nil {
		return x.StuNum
	}
	return ""
}

func (x *BoBingInitRequest) GetNickName() string {
	if x != nil {
		return x.NickName
	}
	return ""
}

func (x *BoBingInitRequest) GetOpenId() string {
	if x != nil {
		return x.OpenId
	}
	return ""
}

type BoBingKeyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Openid string `protobuf:"bytes,1,opt,name=openid,proto3" json:"openid,omitempty"`
}

func (x *BoBingKeyRequest) Reset() {
	*x = BoBingKeyRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_boBing_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BoBingKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BoBingKeyRequest) ProtoMessage() {}

func (x *BoBingKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_boBing_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BoBingKeyRequest.ProtoReflect.Descriptor instead.
func (*BoBingKeyRequest) Descriptor() ([]byte, []int) {
	return file_boBing_proto_rawDescGZIP(), []int{2}
}

func (x *BoBingKeyRequest) GetOpenid() string {
	if x != nil {
		return x.Openid
	}
	return ""
}

type BoBingKeyResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key string `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
}

func (x *BoBingKeyResponse) Reset() {
	*x = BoBingKeyResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_boBing_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BoBingKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BoBingKeyResponse) ProtoMessage() {}

func (x *BoBingKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_boBing_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BoBingKeyResponse.ProtoReflect.Descriptor instead.
func (*BoBingKeyResponse) Descriptor() ([]byte, []int) {
	return file_boBing_proto_rawDescGZIP(), []int{3}
}

func (x *BoBingKeyResponse) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type BoBingPublishRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StuNum   string `protobuf:"bytes,1,opt,name=stuNum,proto3" json:"stuNum,omitempty"`
	NickName string `protobuf:"bytes,2,opt,name=nickName,proto3" json:"nickName,omitempty"`
	Flag     string `protobuf:"bytes,3,opt,name=flag,proto3" json:"flag,omitempty"`
	Check    string `protobuf:"bytes,4,opt,name=check,proto3" json:"check,omitempty"`
	OpenId   string `protobuf:"bytes,5,opt,name=openId,proto3" json:"openId,omitempty"`
}

func (x *BoBingPublishRequest) Reset() {
	*x = BoBingPublishRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_boBing_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BoBingPublishRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BoBingPublishRequest) ProtoMessage() {}

func (x *BoBingPublishRequest) ProtoReflect() protoreflect.Message {
	mi := &file_boBing_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BoBingPublishRequest.ProtoReflect.Descriptor instead.
func (*BoBingPublishRequest) Descriptor() ([]byte, []int) {
	return file_boBing_proto_rawDescGZIP(), []int{4}
}

func (x *BoBingPublishRequest) GetStuNum() string {
	if x != nil {
		return x.StuNum
	}
	return ""
}

func (x *BoBingPublishRequest) GetNickName() string {
	if x != nil {
		return x.NickName
	}
	return ""
}

func (x *BoBingPublishRequest) GetFlag() string {
	if x != nil {
		return x.Flag
	}
	return ""
}

func (x *BoBingPublishRequest) GetCheck() string {
	if x != nil {
		return x.Check
	}
	return ""
}

func (x *BoBingPublishRequest) GetOpenId() string {
	if x != nil {
		return x.OpenId
	}
	return ""
}

type BoBingPublishResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ciphertext string `protobuf:"bytes,1,opt,name=ciphertext,proto3" json:"ciphertext,omitempty"`
}

func (x *BoBingPublishResponse) Reset() {
	*x = BoBingPublishResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_boBing_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BoBingPublishResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BoBingPublishResponse) ProtoMessage() {}

func (x *BoBingPublishResponse) ProtoReflect() protoreflect.Message {
	mi := &file_boBing_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BoBingPublishResponse.ProtoReflect.Descriptor instead.
func (*BoBingPublishResponse) Descriptor() ([]byte, []int) {
	return file_boBing_proto_rawDescGZIP(), []int{5}
}

func (x *BoBingPublishResponse) GetCiphertext() string {
	if x != nil {
		return x.Ciphertext
	}
	return ""
}

type BoBingRank struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NickName string `protobuf:"bytes,1,opt,name=nickName,proto3" json:"nickName,omitempty"`
	Score    int64  `protobuf:"varint,2,opt,name=score,proto3" json:"score,omitempty"`
}

func (x *BoBingRank) Reset() {
	*x = BoBingRank{}
	if protoimpl.UnsafeEnabled {
		mi := &file_boBing_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BoBingRank) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BoBingRank) ProtoMessage() {}

func (x *BoBingRank) ProtoReflect() protoreflect.Message {
	mi := &file_boBing_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BoBingRank.ProtoReflect.Descriptor instead.
func (*BoBingRank) Descriptor() ([]byte, []int) {
	return file_boBing_proto_rawDescGZIP(), []int{6}
}

func (x *BoBingRank) GetNickName() string {
	if x != nil {
		return x.NickName
	}
	return ""
}

func (x *BoBingRank) GetScore() int64 {
	if x != nil {
		return x.Score
	}
	return 0
}

type BoBingMyRank struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NickName string `protobuf:"bytes,1,opt,name=nickName,proto3" json:"nickName,omitempty"`
	Score    int64  `protobuf:"varint,2,opt,name=score,proto3" json:"score,omitempty"`
	Rank     int64  `protobuf:"varint,3,opt,name=rank,proto3" json:"rank,omitempty"`
}

func (x *BoBingMyRank) Reset() {
	*x = BoBingMyRank{}
	if protoimpl.UnsafeEnabled {
		mi := &file_boBing_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BoBingMyRank) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BoBingMyRank) ProtoMessage() {}

func (x *BoBingMyRank) ProtoReflect() protoreflect.Message {
	mi := &file_boBing_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BoBingMyRank.ProtoReflect.Descriptor instead.
func (*BoBingMyRank) Descriptor() ([]byte, []int) {
	return file_boBing_proto_rawDescGZIP(), []int{7}
}

func (x *BoBingMyRank) GetNickName() string {
	if x != nil {
		return x.NickName
	}
	return ""
}

func (x *BoBingMyRank) GetScore() int64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *BoBingMyRank) GetRank() int64 {
	if x != nil {
		return x.Rank
	}
	return 0
}

type BoBingToTalTenResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BoBingRank []*BoBingRank `protobuf:"bytes,1,rep,name=boBingRank,proto3" json:"boBingRank,omitempty"`
	BingMyRank *BoBingMyRank `protobuf:"bytes,2,opt,name=BingMyRank,proto3" json:"BingMyRank,omitempty"`
}

func (x *BoBingToTalTenResponse) Reset() {
	*x = BoBingToTalTenResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_boBing_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BoBingToTalTenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BoBingToTalTenResponse) ProtoMessage() {}

func (x *BoBingToTalTenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_boBing_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BoBingToTalTenResponse.ProtoReflect.Descriptor instead.
func (*BoBingToTalTenResponse) Descriptor() ([]byte, []int) {
	return file_boBing_proto_rawDescGZIP(), []int{8}
}

func (x *BoBingToTalTenResponse) GetBoBingRank() []*BoBingRank {
	if x != nil {
		return x.BoBingRank
	}
	return nil
}

func (x *BoBingToTalTenResponse) GetBingMyRank() *BoBingMyRank {
	if x != nil {
		return x.BingMyRank
	}
	return nil
}

type BoBingDayRankResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BoBingRank []*BoBingRank `protobuf:"bytes,1,rep,name=boBingRank,proto3" json:"boBingRank,omitempty"`
	BingMyRank *BoBingMyRank `protobuf:"bytes,2,opt,name=BingMyRank,proto3" json:"BingMyRank,omitempty"`
}

func (x *BoBingDayRankResponse) Reset() {
	*x = BoBingDayRankResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_boBing_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BoBingDayRankResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BoBingDayRankResponse) ProtoMessage() {}

func (x *BoBingDayRankResponse) ProtoReflect() protoreflect.Message {
	mi := &file_boBing_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BoBingDayRankResponse.ProtoReflect.Descriptor instead.
func (*BoBingDayRankResponse) Descriptor() ([]byte, []int) {
	return file_boBing_proto_rawDescGZIP(), []int{9}
}

func (x *BoBingDayRankResponse) GetBoBingRank() []*BoBingRank {
	if x != nil {
		return x.BoBingRank
	}
	return nil
}

func (x *BoBingDayRankResponse) GetBingMyRank() *BoBingMyRank {
	if x != nil {
		return x.BingMyRank
	}
	return nil
}

type BoBingTianXuan struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NickName string                 `protobuf:"bytes,1,opt,name=nickName,proto3" json:"nickName,omitempty"`
	Types    string                 `protobuf:"bytes,2,opt,name=types,proto3" json:"types,omitempty"`
	Time     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=time,proto3" json:"time,omitempty"`
}

func (x *BoBingTianXuan) Reset() {
	*x = BoBingTianXuan{}
	if protoimpl.UnsafeEnabled {
		mi := &file_boBing_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BoBingTianXuan) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BoBingTianXuan) ProtoMessage() {}

func (x *BoBingTianXuan) ProtoReflect() protoreflect.Message {
	mi := &file_boBing_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BoBingTianXuan.ProtoReflect.Descriptor instead.
func (*BoBingTianXuan) Descriptor() ([]byte, []int) {
	return file_boBing_proto_rawDescGZIP(), []int{10}
}

func (x *BoBingTianXuan) GetNickName() string {
	if x != nil {
		return x.NickName
	}
	return ""
}

func (x *BoBingTianXuan) GetTypes() string {
	if x != nil {
		return x.Types
	}
	return ""
}

func (x *BoBingTianXuan) GetTime() *timestamppb.Timestamp {
	if x != nil {
		return x.Time
	}
	return nil
}

type BoBingTianXuanResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BoBingTianXuan []*BoBingTianXuan `protobuf:"bytes,1,rep,name=boBingTianXuan,proto3" json:"boBingTianXuan,omitempty"`
}

func (x *BoBingTianXuanResponse) Reset() {
	*x = BoBingTianXuanResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_boBing_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BoBingTianXuanResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BoBingTianXuanResponse) ProtoMessage() {}

func (x *BoBingTianXuanResponse) ProtoReflect() protoreflect.Message {
	mi := &file_boBing_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BoBingTianXuanResponse.ProtoReflect.Descriptor instead.
func (*BoBingTianXuanResponse) Descriptor() ([]byte, []int) {
	return file_boBing_proto_rawDescGZIP(), []int{11}
}

func (x *BoBingTianXuanResponse) GetBoBingTianXuan() []*BoBingTianXuan {
	if x != nil {
		return x.BoBingTianXuan
	}
	return nil
}

type BoBingGetCountResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Count int64 `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
}

func (x *BoBingGetCountResponse) Reset() {
	*x = BoBingGetCountResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_boBing_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BoBingGetCountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BoBingGetCountResponse) ProtoMessage() {}

func (x *BoBingGetCountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_boBing_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BoBingGetCountResponse.ProtoReflect.Descriptor instead.
func (*BoBingGetCountResponse) Descriptor() ([]byte, []int) {
	return file_boBing_proto_rawDescGZIP(), []int{12}
}

func (x *BoBingGetCountResponse) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

type BoBingBroadcastCheckRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ciphertext string `protobuf:"bytes,1,opt,name=ciphertext,proto3" json:"ciphertext,omitempty"`
	OpenId     string `protobuf:"bytes,2,opt,name=openId,proto3" json:"openId,omitempty"`
}

func (x *BoBingBroadcastCheckRequest) Reset() {
	*x = BoBingBroadcastCheckRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_boBing_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BoBingBroadcastCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BoBingBroadcastCheckRequest) ProtoMessage() {}

func (x *BoBingBroadcastCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_boBing_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BoBingBroadcastCheckRequest.ProtoReflect.Descriptor instead.
func (*BoBingBroadcastCheckRequest) Descriptor() ([]byte, []int) {
	return file_boBing_proto_rawDescGZIP(), []int{13}
}

func (x *BoBingBroadcastCheckRequest) GetCiphertext() string {
	if x != nil {
		return x.Ciphertext
	}
	return ""
}

func (x *BoBingBroadcastCheckRequest) GetOpenId() string {
	if x != nil {
		return x.OpenId
	}
	return ""
}

type BoBingRecordResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Maps map[string]int64 `protobuf:"bytes,1,rep,name=maps,proto3" json:"maps,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
}

func (x *BoBingRecordResponse) Reset() {
	*x = BoBingRecordResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_boBing_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BoBingRecordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BoBingRecordResponse) ProtoMessage() {}

func (x *BoBingRecordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_boBing_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BoBingRecordResponse.ProtoReflect.Descriptor instead.
func (*BoBingRecordResponse) Descriptor() ([]byte, []int) {
	return file_boBing_proto_rawDescGZIP(), []int{14}
}

func (x *BoBingRecordResponse) GetMaps() map[string]int64 {
	if x != nil {
		return x.Maps
	}
	return nil
}

type BoBingGetNumberResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Number int64 `protobuf:"varint,1,opt,name=number,proto3" json:"number,omitempty"`
}

func (x *BoBingGetNumberResponse) Reset() {
	*x = BoBingGetNumberResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_boBing_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BoBingGetNumberResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BoBingGetNumberResponse) ProtoMessage() {}

func (x *BoBingGetNumberResponse) ProtoReflect() protoreflect.Message {
	mi := &file_boBing_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BoBingGetNumberResponse.ProtoReflect.Descriptor instead.
func (*BoBingGetNumberResponse) Descriptor() ([]byte, []int) {
	return file_boBing_proto_rawDescGZIP(), []int{15}
}

func (x *BoBingGetNumberResponse) GetNumber() int64 {
	if x != nil {
		return x.Number
	}
	return 0
}

var File_boBing_proto protoreflect.FileDescriptor

var file_boBing_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x62, 0x6f, 0x42, 0x69, 0x6e, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1b,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f,
	0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1f, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d,
	0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x2e, 0x0a, 0x12,
	0x42, 0x6f, 0x42, 0x69, 0x6e, 0x67, 0x50, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x5f, 0x0a, 0x11,
	0x42, 0x6f, 0x42, 0x69, 0x6e, 0x67, 0x49, 0x6e, 0x69, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x75, 0x4e, 0x75, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x73, 0x74, 0x75, 0x4e, 0x75, 0x6d, 0x12, 0x1a, 0x0a, 0x08, 0x6e, 0x69, 0x63,
	0x6b, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6e, 0x69, 0x63,
	0x6b, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x70, 0x65, 0x6e, 0x49, 0x64, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6f, 0x70, 0x65, 0x6e, 0x49, 0x64, 0x22, 0x2a, 0x0a,
	0x10, 0x42, 0x6f, 0x42, 0x69, 0x6e, 0x67, 0x4b, 0x65, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x70, 0x65, 0x6e, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x6f, 0x70, 0x65, 0x6e, 0x69, 0x64, 0x22, 0x25, 0x0a, 0x11, 0x42, 0x6f, 0x42,
	0x69, 0x6e, 0x67, 0x4b, 0x65, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x10,
	0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79,
	0x22, 0x8c, 0x01, 0x0a, 0x14, 0x42, 0x6f, 0x42, 0x69, 0x6e, 0x67, 0x50, 0x75, 0x62, 0x6c, 0x69,
	0x73, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x75,
	0x4e, 0x75, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x75, 0x4e, 0x75,
	0x6d, 0x12, 0x1a, 0x0a, 0x08, 0x6e, 0x69, 0x63, 0x6b, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x6e, 0x69, 0x63, 0x6b, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a,
	0x04, 0x66, 0x6c, 0x61, 0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x66, 0x6c, 0x61,
	0x67, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x70, 0x65, 0x6e, 0x49,
	0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6f, 0x70, 0x65, 0x6e, 0x49, 0x64, 0x22,
	0x37, 0x0a, 0x15, 0x42, 0x6f, 0x42, 0x69, 0x6e, 0x67, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x63, 0x69, 0x70, 0x68,
	0x65, 0x72, 0x74, 0x65, 0x78, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x63, 0x69,
	0x70, 0x68, 0x65, 0x72, 0x74, 0x65, 0x78, 0x74, 0x22, 0x3e, 0x0a, 0x0a, 0x42, 0x6f, 0x42, 0x69,
	0x6e, 0x67, 0x52, 0x61, 0x6e, 0x6b, 0x12, 0x1a, 0x0a, 0x08, 0x6e, 0x69, 0x63, 0x6b, 0x4e, 0x61,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6e, 0x69, 0x63, 0x6b, 0x4e, 0x61,
	0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x05, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x22, 0x54, 0x0a, 0x0c, 0x42, 0x6f, 0x42, 0x69,
	0x6e, 0x67, 0x4d, 0x79, 0x52, 0x61, 0x6e, 0x6b, 0x12, 0x1a, 0x0a, 0x08, 0x6e, 0x69, 0x63, 0x6b,
	0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6e, 0x69, 0x63, 0x6b,
	0x4e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x05, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x72, 0x61,
	0x6e, 0x6b, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x72, 0x61, 0x6e, 0x6b, 0x22, 0x74,
	0x0a, 0x16, 0x42, 0x6f, 0x42, 0x69, 0x6e, 0x67, 0x54, 0x6f, 0x54, 0x61, 0x6c, 0x54, 0x65, 0x6e,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2b, 0x0a, 0x0a, 0x62, 0x6f, 0x42, 0x69,
	0x6e, 0x67, 0x52, 0x61, 0x6e, 0x6b, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x42,
	0x6f, 0x42, 0x69, 0x6e, 0x67, 0x52, 0x61, 0x6e, 0x6b, 0x52, 0x0a, 0x62, 0x6f, 0x42, 0x69, 0x6e,
	0x67, 0x52, 0x61, 0x6e, 0x6b, 0x12, 0x2d, 0x0a, 0x0a, 0x42, 0x69, 0x6e, 0x67, 0x4d, 0x79, 0x52,
	0x61, 0x6e, 0x6b, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x42, 0x6f, 0x42, 0x69,
	0x6e, 0x67, 0x4d, 0x79, 0x52, 0x61, 0x6e, 0x6b, 0x52, 0x0a, 0x42, 0x69, 0x6e, 0x67, 0x4d, 0x79,
	0x52, 0x61, 0x6e, 0x6b, 0x22, 0x73, 0x0a, 0x15, 0x42, 0x6f, 0x42, 0x69, 0x6e, 0x67, 0x44, 0x61,
	0x79, 0x52, 0x61, 0x6e, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2b, 0x0a,
	0x0a, 0x62, 0x6f, 0x42, 0x69, 0x6e, 0x67, 0x52, 0x61, 0x6e, 0x6b, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x0b, 0x2e, 0x42, 0x6f, 0x42, 0x69, 0x6e, 0x67, 0x52, 0x61, 0x6e, 0x6b, 0x52, 0x0a,
	0x62, 0x6f, 0x42, 0x69, 0x6e, 0x67, 0x52, 0x61, 0x6e, 0x6b, 0x12, 0x2d, 0x0a, 0x0a, 0x42, 0x69,
	0x6e, 0x67, 0x4d, 0x79, 0x52, 0x61, 0x6e, 0x6b, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d,
	0x2e, 0x42, 0x6f, 0x42, 0x69, 0x6e, 0x67, 0x4d, 0x79, 0x52, 0x61, 0x6e, 0x6b, 0x52, 0x0a, 0x42,
	0x69, 0x6e, 0x67, 0x4d, 0x79, 0x52, 0x61, 0x6e, 0x6b, 0x22, 0x72, 0x0a, 0x0e, 0x42, 0x6f, 0x42,
	0x69, 0x6e, 0x67, 0x54, 0x69, 0x61, 0x6e, 0x58, 0x75, 0x61, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x6e,
	0x69, 0x63, 0x6b, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6e,
	0x69, 0x63, 0x6b, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x79, 0x70, 0x65, 0x73,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x79, 0x70, 0x65, 0x73, 0x12, 0x2e, 0x0a,
	0x04, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69,
	0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x22, 0x51, 0x0a,
	0x16, 0x42, 0x6f, 0x42, 0x69, 0x6e, 0x67, 0x54, 0x69, 0x61, 0x6e, 0x58, 0x75, 0x61, 0x6e, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x37, 0x0a, 0x0e, 0x62, 0x6f, 0x42, 0x69, 0x6e,
	0x67, 0x54, 0x69, 0x61, 0x6e, 0x58, 0x75, 0x61, 0x6e, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x0f, 0x2e, 0x42, 0x6f, 0x42, 0x69, 0x6e, 0x67, 0x54, 0x69, 0x61, 0x6e, 0x58, 0x75, 0x61, 0x6e,
	0x52, 0x0e, 0x62, 0x6f, 0x42, 0x69, 0x6e, 0x67, 0x54, 0x69, 0x61, 0x6e, 0x58, 0x75, 0x61, 0x6e,
	0x22, 0x2e, 0x0a, 0x16, 0x42, 0x6f, 0x42, 0x69, 0x6e, 0x67, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x75,
	0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x22, 0x55, 0x0a, 0x1b, 0x42, 0x6f, 0x42, 0x69, 0x6e, 0x67, 0x42, 0x72, 0x6f, 0x61, 0x64, 0x63,
	0x61, 0x73, 0x74, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x1e, 0x0a, 0x0a, 0x63, 0x69, 0x70, 0x68, 0x65, 0x72, 0x74, 0x65, 0x78, 0x74, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0a, 0x63, 0x69, 0x70, 0x68, 0x65, 0x72, 0x74, 0x65, 0x78, 0x74, 0x12,
	0x16, 0x0a, 0x06, 0x6f, 0x70, 0x65, 0x6e, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x6f, 0x70, 0x65, 0x6e, 0x49, 0x64, 0x22, 0x84, 0x01, 0x0a, 0x14, 0x42, 0x6f, 0x42, 0x69,
	0x6e, 0x67, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x33, 0x0a, 0x04, 0x6d, 0x61, 0x70, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1f,
	0x2e, 0x42, 0x6f, 0x42, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x4d, 0x61, 0x70, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52,
	0x04, 0x6d, 0x61, 0x70, 0x73, 0x1a, 0x37, 0x0a, 0x09, 0x4d, 0x61, 0x70, 0x73, 0x45, 0x6e, 0x74,
	0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x31,
	0x0a, 0x17, 0x42, 0x6f, 0x42, 0x69, 0x6e, 0x67, 0x47, 0x65, 0x74, 0x4e, 0x75, 0x6d, 0x62, 0x65,
	0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x6e, 0x75, 0x6d,
	0x62, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x6e, 0x75, 0x6d, 0x62, 0x65,
	0x72, 0x32, 0xe2, 0x06, 0x0a, 0x0d, 0x42, 0x6f, 0x42, 0x69, 0x6e, 0x67, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x12, 0x39, 0x0a, 0x0a, 0x42, 0x6f, 0x42, 0x69, 0x6e, 0x67, 0x50, 0x69, 0x6e,
	0x67, 0x12, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x13, 0x2e, 0x42, 0x6f, 0x42, 0x69,
	0x6e, 0x67, 0x50, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3e,
	0x0a, 0x0d, 0x42, 0x6f, 0x42, 0x69, 0x6e, 0x67, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x12,
	0x15, 0x2e, 0x42, 0x6f, 0x42, 0x69, 0x6e, 0x67, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x42, 0x6f, 0x42, 0x69, 0x6e, 0x67, 0x50,
	0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x32,
	0x0a, 0x09, 0x42, 0x6f, 0x42, 0x69, 0x6e, 0x67, 0x4b, 0x65, 0x79, 0x12, 0x11, 0x2e, 0x42, 0x6f,
	0x42, 0x69, 0x6e, 0x67, 0x4b, 0x65, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x12,
	0x2e, 0x42, 0x6f, 0x42, 0x69, 0x6e, 0x67, 0x4b, 0x65, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x41, 0x0a, 0x0e, 0x42, 0x6f, 0x42, 0x69, 0x6e, 0x67, 0x54, 0x6f, 0x54, 0x61,
	0x6c, 0x54, 0x65, 0x6e, 0x12, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x17, 0x2e, 0x42,
	0x6f, 0x42, 0x69, 0x6e, 0x67, 0x54, 0x6f, 0x54, 0x61, 0x6c, 0x54, 0x65, 0x6e, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3f, 0x0a, 0x0d, 0x42, 0x6f, 0x42, 0x69, 0x6e, 0x67, 0x44,
	0x61, 0x79, 0x52, 0x61, 0x6e, 0x6b, 0x12, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x16,
	0x2e, 0x42, 0x6f, 0x42, 0x69, 0x6e, 0x67, 0x44, 0x61, 0x79, 0x52, 0x61, 0x6e, 0x6b, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3b, 0x0a, 0x0d, 0x42, 0x6f, 0x42, 0x69, 0x6e, 0x67,
	0x44, 0x61, 0x79, 0x49, 0x6e, 0x69, 0x74, 0x12, 0x12, 0x2e, 0x42, 0x6f, 0x42, 0x69, 0x6e, 0x67,
	0x49, 0x6e, 0x69, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d,
	0x70, 0x74, 0x79, 0x12, 0x41, 0x0a, 0x0e, 0x42, 0x6f, 0x42, 0x69, 0x6e, 0x67, 0x54, 0x69, 0x61,
	0x6e, 0x58, 0x75, 0x61, 0x6e, 0x12, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x17, 0x2e,
	0x42, 0x6f, 0x42, 0x69, 0x6e, 0x67, 0x54, 0x69, 0x61, 0x6e, 0x58, 0x75, 0x61, 0x6e, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x41, 0x0a, 0x0e, 0x42, 0x6f, 0x42, 0x69, 0x6e, 0x67,
	0x47, 0x65, 0x74, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79,
	0x1a, 0x17, 0x2e, 0x42, 0x6f, 0x42, 0x69, 0x6e, 0x67, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x75, 0x6e,
	0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x46, 0x0a, 0x14, 0x42, 0x6f, 0x42,
	0x69, 0x6e, 0x67, 0x52, 0x65, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f,
	0x6e, 0x12, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74,
	0x79, 0x12, 0x4c, 0x0a, 0x14, 0x42, 0x6f, 0x42, 0x69, 0x6e, 0x67, 0x42, 0x72, 0x6f, 0x61, 0x64,
	0x63, 0x61, 0x73, 0x74, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x12, 0x1c, 0x2e, 0x42, 0x6f, 0x42, 0x69,
	0x6e, 0x67, 0x42, 0x72, 0x6f, 0x61, 0x64, 0x63, 0x61, 0x73, 0x74, 0x43, 0x68, 0x65, 0x63, 0x6b,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x12,
	0x3d, 0x0a, 0x0c, 0x42, 0x6f, 0x42, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x12,
	0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x15, 0x2e, 0x42, 0x6f, 0x42, 0x69, 0x6e, 0x67,
	0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x41,
	0x0a, 0x0f, 0x42, 0x6f, 0x42, 0x69, 0x6e, 0x67, 0x42, 0x6c, 0x61, 0x63, 0x6b, 0x6c, 0x69, 0x73,
	0x74, 0x12, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74,
	0x79, 0x12, 0x43, 0x0a, 0x0f, 0x42, 0x6f, 0x42, 0x69, 0x6e, 0x67, 0x47, 0x65, 0x74, 0x4e, 0x75,
	0x6d, 0x62, 0x65, 0x72, 0x12, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x18, 0x2e, 0x42,
	0x6f, 0x42, 0x69, 0x6e, 0x67, 0x47, 0x65, 0x74, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x09, 0x5a, 0x07, 0x62, 0x6f, 0x42, 0x69, 0x6e, 0x67,
	0x2f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_boBing_proto_rawDescOnce sync.Once
	file_boBing_proto_rawDescData = file_boBing_proto_rawDesc
)

func file_boBing_proto_rawDescGZIP() []byte {
	file_boBing_proto_rawDescOnce.Do(func() {
		file_boBing_proto_rawDescData = protoimpl.X.CompressGZIP(file_boBing_proto_rawDescData)
	})
	return file_boBing_proto_rawDescData
}

var file_boBing_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_boBing_proto_goTypes = []interface{}{
	(*BoBingPingResponse)(nil),          // 0: BoBingPingResponse
	(*BoBingInitRequest)(nil),           // 1: BoBingInitRequest
	(*BoBingKeyRequest)(nil),            // 2: BoBingKeyRequest
	(*BoBingKeyResponse)(nil),           // 3: BoBingKeyResponse
	(*BoBingPublishRequest)(nil),        // 4: BoBingPublishRequest
	(*BoBingPublishResponse)(nil),       // 5: BoBingPublishResponse
	(*BoBingRank)(nil),                  // 6: BoBingRank
	(*BoBingMyRank)(nil),                // 7: BoBingMyRank
	(*BoBingToTalTenResponse)(nil),      // 8: BoBingToTalTenResponse
	(*BoBingDayRankResponse)(nil),       // 9: BoBingDayRankResponse
	(*BoBingTianXuan)(nil),              // 10: BoBingTianXuan
	(*BoBingTianXuanResponse)(nil),      // 11: BoBingTianXuanResponse
	(*BoBingGetCountResponse)(nil),      // 12: BoBingGetCountResponse
	(*BoBingBroadcastCheckRequest)(nil), // 13: BoBingBroadcastCheckRequest
	(*BoBingRecordResponse)(nil),        // 14: BoBingRecordResponse
	(*BoBingGetNumberResponse)(nil),     // 15: BoBingGetNumberResponse
	nil,                                 // 16: BoBingRecordResponse.MapsEntry
	(*timestamppb.Timestamp)(nil),       // 17: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),               // 18: google.protobuf.Empty
}
var file_boBing_proto_depIdxs = []int32{
	6,  // 0: BoBingToTalTenResponse.boBingRank:type_name -> BoBingRank
	7,  // 1: BoBingToTalTenResponse.BingMyRank:type_name -> BoBingMyRank
	6,  // 2: BoBingDayRankResponse.boBingRank:type_name -> BoBingRank
	7,  // 3: BoBingDayRankResponse.BingMyRank:type_name -> BoBingMyRank
	17, // 4: BoBingTianXuan.time:type_name -> google.protobuf.Timestamp
	10, // 5: BoBingTianXuanResponse.boBingTianXuan:type_name -> BoBingTianXuan
	16, // 6: BoBingRecordResponse.maps:type_name -> BoBingRecordResponse.MapsEntry
	18, // 7: BoBingService.BoBingPing:input_type -> google.protobuf.Empty
	4,  // 8: BoBingService.BoBingPublish:input_type -> BoBingPublishRequest
	2,  // 9: BoBingService.BoBingKey:input_type -> BoBingKeyRequest
	18, // 10: BoBingService.BoBingToTalTen:input_type -> google.protobuf.Empty
	18, // 11: BoBingService.BoBingDayRank:input_type -> google.protobuf.Empty
	1,  // 12: BoBingService.BoBingDayInit:input_type -> BoBingInitRequest
	18, // 13: BoBingService.BoBingTianXuan:input_type -> google.protobuf.Empty
	18, // 14: BoBingService.BoBingGetCount:input_type -> google.protobuf.Empty
	18, // 15: BoBingService.BoBingRetransmission:input_type -> google.protobuf.Empty
	13, // 16: BoBingService.BoBingBroadcastCheck:input_type -> BoBingBroadcastCheckRequest
	18, // 17: BoBingService.BoBingRecord:input_type -> google.protobuf.Empty
	18, // 18: BoBingService.BoBingBlacklist:input_type -> google.protobuf.Empty
	18, // 19: BoBingService.BoBingGetNumber:input_type -> google.protobuf.Empty
	0,  // 20: BoBingService.BoBingPing:output_type -> BoBingPingResponse
	5,  // 21: BoBingService.BoBingPublish:output_type -> BoBingPublishResponse
	3,  // 22: BoBingService.BoBingKey:output_type -> BoBingKeyResponse
	8,  // 23: BoBingService.BoBingToTalTen:output_type -> BoBingToTalTenResponse
	9,  // 24: BoBingService.BoBingDayRank:output_type -> BoBingDayRankResponse
	18, // 25: BoBingService.BoBingDayInit:output_type -> google.protobuf.Empty
	11, // 26: BoBingService.BoBingTianXuan:output_type -> BoBingTianXuanResponse
	12, // 27: BoBingService.BoBingGetCount:output_type -> BoBingGetCountResponse
	18, // 28: BoBingService.BoBingRetransmission:output_type -> google.protobuf.Empty
	18, // 29: BoBingService.BoBingBroadcastCheck:output_type -> google.protobuf.Empty
	14, // 30: BoBingService.BoBingRecord:output_type -> BoBingRecordResponse
	18, // 31: BoBingService.BoBingBlacklist:output_type -> google.protobuf.Empty
	15, // 32: BoBingService.BoBingGetNumber:output_type -> BoBingGetNumberResponse
	20, // [20:33] is the sub-list for method output_type
	7,  // [7:20] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_boBing_proto_init() }
func file_boBing_proto_init() {
	if File_boBing_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_boBing_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BoBingPingResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_boBing_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BoBingInitRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_boBing_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BoBingKeyRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_boBing_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BoBingKeyResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_boBing_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BoBingPublishRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_boBing_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BoBingPublishResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_boBing_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BoBingRank); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_boBing_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BoBingMyRank); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_boBing_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BoBingToTalTenResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_boBing_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BoBingDayRankResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_boBing_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BoBingTianXuan); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_boBing_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BoBingTianXuanResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_boBing_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BoBingGetCountResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_boBing_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BoBingBroadcastCheckRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_boBing_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BoBingRecordResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_boBing_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BoBingGetNumberResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_boBing_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_boBing_proto_goTypes,
		DependencyIndexes: file_boBing_proto_depIdxs,
		MessageInfos:      file_boBing_proto_msgTypes,
	}.Build()
	File_boBing_proto = out.File
	file_boBing_proto_rawDesc = nil
	file_boBing_proto_goTypes = nil
	file_boBing_proto_depIdxs = nil
}
