// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v4.23.2
// source: yearBill.proto

package yearBill

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type YearBillPingResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *YearBillPingResponse) Reset() {
	*x = YearBillPingResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_yearBill_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *YearBillPingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*YearBillPingResponse) ProtoMessage() {}

func (x *YearBillPingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_yearBill_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use YearBillPingResponse.ProtoReflect.Descriptor instead.
func (*YearBillPingResponse) Descriptor() ([]byte, []int) {
	return file_yearBill_proto_rawDescGZIP(), []int{0}
}

func (x *YearBillPingResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type InfoCheckRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StuNum string `protobuf:"bytes,1,opt,name=stu_num,json=stuNum,proto3" json:"stu_num,omitempty"`
}

func (x *InfoCheckRequest) Reset() {
	*x = InfoCheckRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_yearBill_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InfoCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InfoCheckRequest) ProtoMessage() {}

func (x *InfoCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_yearBill_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InfoCheckRequest.ProtoReflect.Descriptor instead.
func (*InfoCheckRequest) Descriptor() ([]byte, []int) {
	return file_yearBill_proto_rawDescGZIP(), []int{1}
}

func (x *InfoCheckRequest) GetStuNum() string {
	if x != nil {
		return x.StuNum
	}
	return ""
}

type InfoCheckResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Flag bool `protobuf:"varint,1,opt,name=flag,proto3" json:"flag,omitempty"`
}

func (x *InfoCheckResponse) Reset() {
	*x = InfoCheckResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_yearBill_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InfoCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InfoCheckResponse) ProtoMessage() {}

func (x *InfoCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_yearBill_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InfoCheckResponse.ProtoReflect.Descriptor instead.
func (*InfoCheckResponse) Descriptor() ([]byte, []int) {
	return file_yearBill_proto_rawDescGZIP(), []int{2}
}

func (x *InfoCheckResponse) GetFlag() bool {
	if x != nil {
		return x.Flag
	}
	return false
}

type GetCertificateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Openid string `protobuf:"bytes,1,opt,name=openid,proto3" json:"openid,omitempty"`
	StuNum string `protobuf:"bytes,2,opt,name=stu_num,json=stuNum,proto3" json:"stu_num,omitempty"`
}

func (x *GetCertificateRequest) Reset() {
	*x = GetCertificateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_yearBill_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCertificateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCertificateRequest) ProtoMessage() {}

func (x *GetCertificateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_yearBill_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCertificateRequest.ProtoReflect.Descriptor instead.
func (*GetCertificateRequest) Descriptor() ([]byte, []int) {
	return file_yearBill_proto_rawDescGZIP(), []int{3}
}

func (x *GetCertificateRequest) GetOpenid() string {
	if x != nil {
		return x.Openid
	}
	return ""
}

func (x *GetCertificateRequest) GetStuNum() string {
	if x != nil {
		return x.StuNum
	}
	return ""
}

type GetCertificateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	JsSessionId  string `protobuf:"bytes,1,opt,name=jsSessionId,proto3" json:"jsSessionId,omitempty"`
	HallTicket   string `protobuf:"bytes,2,opt,name=hallTicket,proto3" json:"hallTicket,omitempty"`
	GsSession    string `protobuf:"bytes,3,opt,name=gsSession,proto3" json:"gsSession,omitempty"`
	Emaphome_WEU string `protobuf:"bytes,4,opt,name=emaphome_WEU,json=emaphomeWEU,proto3" json:"emaphome_WEU,omitempty"`
}

func (x *GetCertificateResponse) Reset() {
	*x = GetCertificateResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_yearBill_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCertificateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCertificateResponse) ProtoMessage() {}

func (x *GetCertificateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_yearBill_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCertificateResponse.ProtoReflect.Descriptor instead.
func (*GetCertificateResponse) Descriptor() ([]byte, []int) {
	return file_yearBill_proto_rawDescGZIP(), []int{4}
}

func (x *GetCertificateResponse) GetJsSessionId() string {
	if x != nil {
		return x.JsSessionId
	}
	return ""
}

func (x *GetCertificateResponse) GetHallTicket() string {
	if x != nil {
		return x.HallTicket
	}
	return ""
}

func (x *GetCertificateResponse) GetGsSession() string {
	if x != nil {
		return x.GsSession
	}
	return ""
}

func (x *GetCertificateResponse) GetEmaphome_WEU() string {
	if x != nil {
		return x.Emaphome_WEU
	}
	return ""
}

type DataInitRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	JsSessionId  string `protobuf:"bytes,1,opt,name=jsSessionId,proto3" json:"jsSessionId,omitempty"`
	HallTicket   string `protobuf:"bytes,2,opt,name=hallTicket,proto3" json:"hallTicket,omitempty"`
	GsSession    string `protobuf:"bytes,3,opt,name=gsSession,proto3" json:"gsSession,omitempty"`
	Emaphome_WEU string `protobuf:"bytes,4,opt,name=emaphome_WEU,json=emaphomeWEU,proto3" json:"emaphome_WEU,omitempty"`
	StuNum       string `protobuf:"bytes,5,opt,name=stu_num,json=stuNum,proto3" json:"stu_num,omitempty"`
}

func (x *DataInitRequest) Reset() {
	*x = DataInitRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_yearBill_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DataInitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataInitRequest) ProtoMessage() {}

func (x *DataInitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_yearBill_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataInitRequest.ProtoReflect.Descriptor instead.
func (*DataInitRequest) Descriptor() ([]byte, []int) {
	return file_yearBill_proto_rawDescGZIP(), []int{5}
}

func (x *DataInitRequest) GetJsSessionId() string {
	if x != nil {
		return x.JsSessionId
	}
	return ""
}

func (x *DataInitRequest) GetHallTicket() string {
	if x != nil {
		return x.HallTicket
	}
	return ""
}

func (x *DataInitRequest) GetGsSession() string {
	if x != nil {
		return x.GsSession
	}
	return ""
}

func (x *DataInitRequest) GetEmaphome_WEU() string {
	if x != nil {
		return x.Emaphome_WEU
	}
	return ""
}

func (x *DataInitRequest) GetStuNum() string {
	if x != nil {
		return x.StuNum
	}
	return ""
}

type PayDataInitRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StuNum     string `protobuf:"bytes,2,opt,name=stu_num,json=stuNum,proto3" json:"stu_num,omitempty"`
	HallTicket string `protobuf:"bytes,1,opt,name=hall_ticket,json=hallTicket,proto3" json:"hall_ticket,omitempty"`
}

func (x *PayDataInitRequest) Reset() {
	*x = PayDataInitRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_yearBill_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PayDataInitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PayDataInitRequest) ProtoMessage() {}

func (x *PayDataInitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_yearBill_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PayDataInitRequest.ProtoReflect.Descriptor instead.
func (*PayDataInitRequest) Descriptor() ([]byte, []int) {
	return file_yearBill_proto_rawDescGZIP(), []int{6}
}

func (x *PayDataInitRequest) GetStuNum() string {
	if x != nil {
		return x.StuNum
	}
	return ""
}

func (x *PayDataInitRequest) GetHallTicket() string {
	if x != nil {
		return x.HallTicket
	}
	return ""
}

type PayDataInitResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Flag                  int64                  `protobuf:"varint,1,opt,name=flag,proto3" json:"flag,omitempty"`
	FavoriteRestaurant    string                 `protobuf:"bytes,2,opt,name=favorite_restaurant,json=favoriteRestaurant,proto3" json:"favorite_restaurant,omitempty"`
	FavoriteRestaurantPay float64                `protobuf:"fixed64,7,opt,name=favorite_restaurant_pay,json=favoriteRestaurantPay,proto3" json:"favorite_restaurant_pay,omitempty"`
	EarlyTime             *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=earlyTime,proto3" json:"earlyTime,omitempty"`
	LastTime              *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=lastTime,proto3" json:"lastTime,omitempty"`
	OtherPay              float64                `protobuf:"fixed64,5,opt,name=other_pay,json=otherPay,proto3" json:"other_pay,omitempty"`
	RestaurantPay         float64                `protobuf:"fixed64,6,opt,name=restaurant_pay,json=restaurantPay,proto3" json:"restaurant_pay,omitempty"`
	LibraryPay            float64                `protobuf:"fixed64,8,opt,name=library_pay,json=libraryPay,proto3" json:"library_pay,omitempty"`
}

func (x *PayDataInitResponse) Reset() {
	*x = PayDataInitResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_yearBill_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PayDataInitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PayDataInitResponse) ProtoMessage() {}

func (x *PayDataInitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_yearBill_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PayDataInitResponse.ProtoReflect.Descriptor instead.
func (*PayDataInitResponse) Descriptor() ([]byte, []int) {
	return file_yearBill_proto_rawDescGZIP(), []int{7}
}

func (x *PayDataInitResponse) GetFlag() int64 {
	if x != nil {
		return x.Flag
	}
	return 0
}

func (x *PayDataInitResponse) GetFavoriteRestaurant() string {
	if x != nil {
		return x.FavoriteRestaurant
	}
	return ""
}

func (x *PayDataInitResponse) GetFavoriteRestaurantPay() float64 {
	if x != nil {
		return x.FavoriteRestaurantPay
	}
	return 0
}

func (x *PayDataInitResponse) GetEarlyTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EarlyTime
	}
	return nil
}

func (x *PayDataInitResponse) GetLastTime() *timestamppb.Timestamp {
	if x != nil {
		return x.LastTime
	}
	return nil
}

func (x *PayDataInitResponse) GetOtherPay() float64 {
	if x != nil {
		return x.OtherPay
	}
	return 0
}

func (x *PayDataInitResponse) GetRestaurantPay() float64 {
	if x != nil {
		return x.RestaurantPay
	}
	return 0
}

func (x *PayDataInitResponse) GetLibraryPay() float64 {
	if x != nil {
		return x.LibraryPay
	}
	return 0
}

type BookDataInitRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StuNum      string `protobuf:"bytes,2,opt,name=stu_num,json=stuNum,proto3" json:"stu_num,omitempty"`
	JsSessionid string `protobuf:"bytes,1,opt,name=jsSessionid,proto3" json:"jsSessionid,omitempty"`
}

func (x *BookDataInitRequest) Reset() {
	*x = BookDataInitRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_yearBill_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BookDataInitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookDataInitRequest) ProtoMessage() {}

func (x *BookDataInitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_yearBill_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookDataInitRequest.ProtoReflect.Descriptor instead.
func (*BookDataInitRequest) Descriptor() ([]byte, []int) {
	return file_yearBill_proto_rawDescGZIP(), []int{8}
}

func (x *BookDataInitRequest) GetStuNum() string {
	if x != nil {
		return x.StuNum
	}
	return ""
}

func (x *BookDataInitRequest) GetJsSessionid() string {
	if x != nil {
		return x.JsSessionid
	}
	return ""
}

type BookDataInitResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Flag int64 `protobuf:"varint,1,opt,name=flag,proto3" json:"flag,omitempty"`
}

func (x *BookDataInitResponse) Reset() {
	*x = BookDataInitResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_yearBill_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BookDataInitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookDataInitResponse) ProtoMessage() {}

func (x *BookDataInitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_yearBill_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookDataInitResponse.ProtoReflect.Descriptor instead.
func (*BookDataInitResponse) Descriptor() ([]byte, []int) {
	return file_yearBill_proto_rawDescGZIP(), []int{9}
}

func (x *BookDataInitResponse) GetFlag() int64 {
	if x != nil {
		return x.Flag
	}
	return 0
}

type LearnDataInitRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StuNum       string `protobuf:"bytes,3,opt,name=stu_num,json=stuNum,proto3" json:"stu_num,omitempty"`
	GsSession    string `protobuf:"bytes,1,opt,name=gsSession,proto3" json:"gsSession,omitempty"`
	Emaphome_WEU string `protobuf:"bytes,2,opt,name=emaphome_WEU,json=emaphomeWEU,proto3" json:"emaphome_WEU,omitempty"`
}

func (x *LearnDataInitRequest) Reset() {
	*x = LearnDataInitRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_yearBill_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LearnDataInitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LearnDataInitRequest) ProtoMessage() {}

func (x *LearnDataInitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_yearBill_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LearnDataInitRequest.ProtoReflect.Descriptor instead.
func (*LearnDataInitRequest) Descriptor() ([]byte, []int) {
	return file_yearBill_proto_rawDescGZIP(), []int{10}
}

func (x *LearnDataInitRequest) GetStuNum() string {
	if x != nil {
		return x.StuNum
	}
	return ""
}

func (x *LearnDataInitRequest) GetGsSession() string {
	if x != nil {
		return x.GsSession
	}
	return ""
}

func (x *LearnDataInitRequest) GetEmaphome_WEU() string {
	if x != nil {
		return x.Emaphome_WEU
	}
	return ""
}

type LearnDataInitResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MostCourse string `protobuf:"bytes,4,opt,name=most_course,json=mostCourse,proto3" json:"most_course,omitempty"`
	Eight      int64  `protobuf:"varint,1,opt,name=eight,proto3" json:"eight,omitempty"`
	Ten        int64  `protobuf:"varint,2,opt,name=ten,proto3" json:"ten,omitempty"`
	SumLesson  int64  `protobuf:"varint,3,opt,name=sum_lesson,json=sumLesson,proto3" json:"sum_lesson,omitempty"`
	Most       int64  `protobuf:"varint,5,opt,name=most,proto3" json:"most,omitempty"`
	Flag       int64  `protobuf:"varint,6,opt,name=flag,proto3" json:"flag,omitempty"`
}

func (x *LearnDataInitResponse) Reset() {
	*x = LearnDataInitResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_yearBill_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LearnDataInitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LearnDataInitResponse) ProtoMessage() {}

func (x *LearnDataInitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_yearBill_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LearnDataInitResponse.ProtoReflect.Descriptor instead.
func (*LearnDataInitResponse) Descriptor() ([]byte, []int) {
	return file_yearBill_proto_rawDescGZIP(), []int{11}
}

func (x *LearnDataInitResponse) GetMostCourse() string {
	if x != nil {
		return x.MostCourse
	}
	return ""
}

func (x *LearnDataInitResponse) GetEight() int64 {
	if x != nil {
		return x.Eight
	}
	return 0
}

func (x *LearnDataInitResponse) GetTen() int64 {
	if x != nil {
		return x.Ten
	}
	return 0
}

func (x *LearnDataInitResponse) GetSumLesson() int64 {
	if x != nil {
		return x.SumLesson
	}
	return 0
}

func (x *LearnDataInitResponse) GetMost() int64 {
	if x != nil {
		return x.Most
	}
	return 0
}

func (x *LearnDataInitResponse) GetFlag() int64 {
	if x != nil {
		return x.Flag
	}
	return 0
}

type DataStorageRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StuNum    string                 `protobuf:"bytes,3,opt,name=stu_num,json=stuNum,proto3" json:"stu_num,omitempty"`
	LearnData *LearnDataInitResponse `protobuf:"bytes,1,opt,name=learn_data,json=learnData,proto3" json:"learn_data,omitempty"`
	PayData   *PayDataInitResponse   `protobuf:"bytes,2,opt,name=pay_data,json=payData,proto3" json:"pay_data,omitempty"`
}

func (x *DataStorageRequest) Reset() {
	*x = DataStorageRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_yearBill_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DataStorageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataStorageRequest) ProtoMessage() {}

func (x *DataStorageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_yearBill_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataStorageRequest.ProtoReflect.Descriptor instead.
func (*DataStorageRequest) Descriptor() ([]byte, []int) {
	return file_yearBill_proto_rawDescGZIP(), []int{12}
}

func (x *DataStorageRequest) GetStuNum() string {
	if x != nil {
		return x.StuNum
	}
	return ""
}

func (x *DataStorageRequest) GetLearnData() *LearnDataInitResponse {
	if x != nil {
		return x.LearnData
	}
	return nil
}

func (x *DataStorageRequest) GetPayData() *PayDataInitResponse {
	if x != nil {
		return x.PayData
	}
	return nil
}

type GetBookDataResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Read    int64  `protobuf:"varint,1,opt,name=read,proto3" json:"read,omitempty"`
	Reading int64  `protobuf:"varint,2,opt,name=reading,proto3" json:"reading,omitempty"`
	Longest string `protobuf:"bytes,3,opt,name=longest,proto3" json:"longest,omitempty"`
	Day     int64  `protobuf:"varint,4,opt,name=day,proto3" json:"day,omitempty"`
}

func (x *GetBookDataResponse) Reset() {
	*x = GetBookDataResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_yearBill_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBookDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBookDataResponse) ProtoMessage() {}

func (x *GetBookDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_yearBill_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBookDataResponse.ProtoReflect.Descriptor instead.
func (*GetBookDataResponse) Descriptor() ([]byte, []int) {
	return file_yearBill_proto_rawDescGZIP(), []int{13}
}

func (x *GetBookDataResponse) GetRead() int64 {
	if x != nil {
		return x.Read
	}
	return 0
}

func (x *GetBookDataResponse) GetReading() int64 {
	if x != nil {
		return x.Reading
	}
	return 0
}

func (x *GetBookDataResponse) GetLongest() string {
	if x != nil {
		return x.Longest
	}
	return ""
}

func (x *GetBookDataResponse) GetDay() int64 {
	if x != nil {
		return x.Day
	}
	return 0
}

type GetPayDataRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StuNum string `protobuf:"bytes,1,opt,name=stu_num,json=stuNum,proto3" json:"stu_num,omitempty"`
}

func (x *GetPayDataRequest) Reset() {
	*x = GetPayDataRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_yearBill_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPayDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPayDataRequest) ProtoMessage() {}

func (x *GetPayDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_yearBill_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPayDataRequest.ProtoReflect.Descriptor instead.
func (*GetPayDataRequest) Descriptor() ([]byte, []int) {
	return file_yearBill_proto_rawDescGZIP(), []int{14}
}

func (x *GetPayDataRequest) GetStuNum() string {
	if x != nil {
		return x.StuNum
	}
	return ""
}

type GetPayDataResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FavoriteRestaurant    string                 `protobuf:"bytes,1,opt,name=favorite_restaurant,json=favoriteRestaurant,proto3" json:"favorite_restaurant,omitempty"`
	EarlyTime             *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=earlyTime,proto3" json:"earlyTime,omitempty"`
	LastTime              *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=lastTime,proto3" json:"lastTime,omitempty"`
	FavoriteRestaurantPay float64                `protobuf:"fixed64,4,opt,name=favorite_restaurant_pay,json=favoriteRestaurantPay,proto3" json:"favorite_restaurant_pay,omitempty"`
	OtherPay              float64                `protobuf:"fixed64,5,opt,name=other_pay,json=otherPay,proto3" json:"other_pay,omitempty"`
	RestaurantPay         float64                `protobuf:"fixed64,6,opt,name=restaurant_pay,json=restaurantPay,proto3" json:"restaurant_pay,omitempty"`
	LibraryPay            float64                `protobuf:"fixed64,7,opt,name=library_pay,json=libraryPay,proto3" json:"library_pay,omitempty"`
}

func (x *GetPayDataResponse) Reset() {
	*x = GetPayDataResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_yearBill_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPayDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPayDataResponse) ProtoMessage() {}

func (x *GetPayDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_yearBill_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPayDataResponse.ProtoReflect.Descriptor instead.
func (*GetPayDataResponse) Descriptor() ([]byte, []int) {
	return file_yearBill_proto_rawDescGZIP(), []int{15}
}

func (x *GetPayDataResponse) GetFavoriteRestaurant() string {
	if x != nil {
		return x.FavoriteRestaurant
	}
	return ""
}

func (x *GetPayDataResponse) GetEarlyTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EarlyTime
	}
	return nil
}

func (x *GetPayDataResponse) GetLastTime() *timestamppb.Timestamp {
	if x != nil {
		return x.LastTime
	}
	return nil
}

func (x *GetPayDataResponse) GetFavoriteRestaurantPay() float64 {
	if x != nil {
		return x.FavoriteRestaurantPay
	}
	return 0
}

func (x *GetPayDataResponse) GetOtherPay() float64 {
	if x != nil {
		return x.OtherPay
	}
	return 0
}

func (x *GetPayDataResponse) GetRestaurantPay() float64 {
	if x != nil {
		return x.RestaurantPay
	}
	return 0
}

func (x *GetPayDataResponse) GetLibraryPay() float64 {
	if x != nil {
		return x.LibraryPay
	}
	return 0
}

type GetLearnDataRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StuNum string `protobuf:"bytes,1,opt,name=stu_num,json=stuNum,proto3" json:"stu_num,omitempty"`
}

func (x *GetLearnDataRequest) Reset() {
	*x = GetLearnDataRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_yearBill_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetLearnDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLearnDataRequest) ProtoMessage() {}

func (x *GetLearnDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_yearBill_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLearnDataRequest.ProtoReflect.Descriptor instead.
func (*GetLearnDataRequest) Descriptor() ([]byte, []int) {
	return file_yearBill_proto_rawDescGZIP(), []int{16}
}

func (x *GetLearnDataRequest) GetStuNum() string {
	if x != nil {
		return x.StuNum
	}
	return ""
}

type GetLearnDataResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MostCourse string `protobuf:"bytes,4,opt,name=most_course,json=mostCourse,proto3" json:"most_course,omitempty"`
	Most       int64  `protobuf:"varint,5,opt,name=most,proto3" json:"most,omitempty"`
	Eight      int64  `protobuf:"varint,1,opt,name=eight,proto3" json:"eight,omitempty"`
	Ten        int64  `protobuf:"varint,2,opt,name=ten,proto3" json:"ten,omitempty"`
	SumLesson  int64  `protobuf:"varint,3,opt,name=sum_lesson,json=sumLesson,proto3" json:"sum_lesson,omitempty"`
}

func (x *GetLearnDataResponse) Reset() {
	*x = GetLearnDataResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_yearBill_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetLearnDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLearnDataResponse) ProtoMessage() {}

func (x *GetLearnDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_yearBill_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLearnDataResponse.ProtoReflect.Descriptor instead.
func (*GetLearnDataResponse) Descriptor() ([]byte, []int) {
	return file_yearBill_proto_rawDescGZIP(), []int{17}
}

func (x *GetLearnDataResponse) GetMostCourse() string {
	if x != nil {
		return x.MostCourse
	}
	return ""
}

func (x *GetLearnDataResponse) GetMost() int64 {
	if x != nil {
		return x.Most
	}
	return 0
}

func (x *GetLearnDataResponse) GetEight() int64 {
	if x != nil {
		return x.Eight
	}
	return 0
}

func (x *GetLearnDataResponse) GetTen() int64 {
	if x != nil {
		return x.Ten
	}
	return 0
}

func (x *GetLearnDataResponse) GetSumLesson() int64 {
	if x != nil {
		return x.SumLesson
	}
	return 0
}

type GetRankRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StuNum string `protobuf:"bytes,1,opt,name=stu_num,json=stuNum,proto3" json:"stu_num,omitempty"`
}

func (x *GetRankRequest) Reset() {
	*x = GetRankRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_yearBill_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRankRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRankRequest) ProtoMessage() {}

func (x *GetRankRequest) ProtoReflect() protoreflect.Message {
	mi := &file_yearBill_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRankRequest.ProtoReflect.Descriptor instead.
func (*GetRankRequest) Descriptor() ([]byte, []int) {
	return file_yearBill_proto_rawDescGZIP(), []int{18}
}

func (x *GetRankRequest) GetStuNum() string {
	if x != nil {
		return x.StuNum
	}
	return ""
}

type GetRankResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Index     int64 `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Appraisal int64 `protobuf:"varint,2,opt,name=appraisal,proto3" json:"appraisal,omitempty"`
	Count     int64 `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
}

func (x *GetRankResponse) Reset() {
	*x = GetRankResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_yearBill_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRankResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRankResponse) ProtoMessage() {}

func (x *GetRankResponse) ProtoReflect() protoreflect.Message {
	mi := &file_yearBill_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRankResponse.ProtoReflect.Descriptor instead.
func (*GetRankResponse) Descriptor() ([]byte, []int) {
	return file_yearBill_proto_rawDescGZIP(), []int{19}
}

func (x *GetRankResponse) GetIndex() int64 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *GetRankResponse) GetAppraisal() int64 {
	if x != nil {
		return x.Appraisal
	}
	return 0
}

func (x *GetRankResponse) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

type AppraiseRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StuNum    string `protobuf:"bytes,1,opt,name=stu_num,json=stuNum,proto3" json:"stu_num,omitempty"`
	Appraisal int64  `protobuf:"varint,2,opt,name=appraisal,proto3" json:"appraisal,omitempty"`
}

func (x *AppraiseRequest) Reset() {
	*x = AppraiseRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_yearBill_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AppraiseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppraiseRequest) ProtoMessage() {}

func (x *AppraiseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_yearBill_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppraiseRequest.ProtoReflect.Descriptor instead.
func (*AppraiseRequest) Descriptor() ([]byte, []int) {
	return file_yearBill_proto_rawDescGZIP(), []int{20}
}

func (x *AppraiseRequest) GetStuNum() string {
	if x != nil {
		return x.StuNum
	}
	return ""
}

func (x *AppraiseRequest) GetAppraisal() int64 {
	if x != nil {
		return x.Appraisal
	}
	return 0
}

type CheckStateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StuNum string `protobuf:"bytes,1,opt,name=stu_num,json=stuNum,proto3" json:"stu_num,omitempty"`
}

func (x *CheckStateRequest) Reset() {
	*x = CheckStateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_yearBill_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckStateRequest) ProtoMessage() {}

func (x *CheckStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_yearBill_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckStateRequest.ProtoReflect.Descriptor instead.
func (*CheckStateRequest) Descriptor() ([]byte, []int) {
	return file_yearBill_proto_rawDescGZIP(), []int{21}
}

func (x *CheckStateRequest) GetStuNum() string {
	if x != nil {
		return x.StuNum
	}
	return ""
}

type CheckStateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	State bool `protobuf:"varint,1,opt,name=state,proto3" json:"state,omitempty"`
}

func (x *CheckStateResponse) Reset() {
	*x = CheckStateResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_yearBill_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckStateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckStateResponse) ProtoMessage() {}

func (x *CheckStateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_yearBill_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckStateResponse.ProtoReflect.Descriptor instead.
func (*CheckStateResponse) Descriptor() ([]byte, []int) {
	return file_yearBill_proto_rawDescGZIP(), []int{22}
}

func (x *CheckStateResponse) GetState() bool {
	if x != nil {
		return x.State
	}
	return false
}

var File_yearBill_proto protoreflect.FileDescriptor

var file_yearBill_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x79, 0x65, 0x61, 0x72, 0x42, 0x69, 0x6c, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x30,
	0x0a, 0x14, 0x59, 0x65, 0x61, 0x72, 0x42, 0x69, 0x6c, 0x6c, 0x50, 0x69, 0x6e, 0x67, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x22, 0x2b, 0x0a, 0x10, 0x49, 0x6e, 0x66, 0x6f, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x73, 0x74, 0x75, 0x5f, 0x6e, 0x75, 0x6d, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x75, 0x4e, 0x75, 0x6d, 0x22, 0x27, 0x0a,
	0x11, 0x49, 0x6e, 0x66, 0x6f, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x66, 0x6c, 0x61, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x04, 0x66, 0x6c, 0x61, 0x67, 0x22, 0x48, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x43, 0x65, 0x72,
	0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x16, 0x0a, 0x06, 0x6f, 0x70, 0x65, 0x6e, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x6f, 0x70, 0x65, 0x6e, 0x69, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x73, 0x74, 0x75, 0x5f, 0x6e,
	0x75, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x75, 0x4e, 0x75, 0x6d,
	0x22, 0x9b, 0x01, 0x0a, 0x16, 0x47, 0x65, 0x74, 0x43, 0x65, 0x72, 0x74, 0x69, 0x66, 0x69, 0x63,
	0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x6a,
	0x73, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0b, 0x6a, 0x73, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x1e, 0x0a,
	0x0a, 0x68, 0x61, 0x6c, 0x6c, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0a, 0x68, 0x61, 0x6c, 0x6c, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x12, 0x1c, 0x0a,
	0x09, 0x67, 0x73, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x67, 0x73, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x21, 0x0a, 0x0c, 0x65,
	0x6d, 0x61, 0x70, 0x68, 0x6f, 0x6d, 0x65, 0x5f, 0x57, 0x45, 0x55, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0b, 0x65, 0x6d, 0x61, 0x70, 0x68, 0x6f, 0x6d, 0x65, 0x57, 0x45, 0x55, 0x22, 0xad,
	0x01, 0x0a, 0x0f, 0x44, 0x61, 0x74, 0x61, 0x49, 0x6e, 0x69, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x20, 0x0a, 0x0b, 0x6a, 0x73, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x6a, 0x73, 0x53, 0x65, 0x73, 0x73, 0x69,
	0x6f, 0x6e, 0x49, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x68, 0x61, 0x6c, 0x6c, 0x54, 0x69, 0x63, 0x6b,
	0x65, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x68, 0x61, 0x6c, 0x6c, 0x54, 0x69,
	0x63, 0x6b, 0x65, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x67, 0x73, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f,
	0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x67, 0x73, 0x53, 0x65, 0x73, 0x73, 0x69,
	0x6f, 0x6e, 0x12, 0x21, 0x0a, 0x0c, 0x65, 0x6d, 0x61, 0x70, 0x68, 0x6f, 0x6d, 0x65, 0x5f, 0x57,
	0x45, 0x55, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x65, 0x6d, 0x61, 0x70, 0x68, 0x6f,
	0x6d, 0x65, 0x57, 0x45, 0x55, 0x12, 0x17, 0x0a, 0x07, 0x73, 0x74, 0x75, 0x5f, 0x6e, 0x75, 0x6d,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x75, 0x4e, 0x75, 0x6d, 0x22, 0x4e,
	0x0a, 0x12, 0x50, 0x61, 0x79, 0x44, 0x61, 0x74, 0x61, 0x49, 0x6e, 0x69, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x73, 0x74, 0x75, 0x5f, 0x6e, 0x75, 0x6d, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x75, 0x4e, 0x75, 0x6d, 0x12, 0x1f, 0x0a,
	0x0b, 0x68, 0x61, 0x6c, 0x6c, 0x5f, 0x74, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0a, 0x68, 0x61, 0x6c, 0x6c, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x22, 0xe9,
	0x02, 0x0a, 0x13, 0x50, 0x61, 0x79, 0x44, 0x61, 0x74, 0x61, 0x49, 0x6e, 0x69, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x66, 0x6c, 0x61, 0x67, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x66, 0x6c, 0x61, 0x67, 0x12, 0x2f, 0x0a, 0x13, 0x66, 0x61,
	0x76, 0x6f, 0x72, 0x69, 0x74, 0x65, 0x5f, 0x72, 0x65, 0x73, 0x74, 0x61, 0x75, 0x72, 0x61, 0x6e,
	0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x12, 0x66, 0x61, 0x76, 0x6f, 0x72, 0x69, 0x74,
	0x65, 0x52, 0x65, 0x73, 0x74, 0x61, 0x75, 0x72, 0x61, 0x6e, 0x74, 0x12, 0x36, 0x0a, 0x17, 0x66,
	0x61, 0x76, 0x6f, 0x72, 0x69, 0x74, 0x65, 0x5f, 0x72, 0x65, 0x73, 0x74, 0x61, 0x75, 0x72, 0x61,
	0x6e, 0x74, 0x5f, 0x70, 0x61, 0x79, 0x18, 0x07, 0x20, 0x01, 0x28, 0x01, 0x52, 0x15, 0x66, 0x61,
	0x76, 0x6f, 0x72, 0x69, 0x74, 0x65, 0x52, 0x65, 0x73, 0x74, 0x61, 0x75, 0x72, 0x61, 0x6e, 0x74,
	0x50, 0x61, 0x79, 0x12, 0x38, 0x0a, 0x09, 0x65, 0x61, 0x72, 0x6c, 0x79, 0x54, 0x69, 0x6d, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x52, 0x09, 0x65, 0x61, 0x72, 0x6c, 0x79, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x36, 0x0a,
	0x08, 0x6c, 0x61, 0x73, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x08, 0x6c, 0x61, 0x73,
	0x74, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x6f, 0x74, 0x68, 0x65, 0x72, 0x5f, 0x70,
	0x61, 0x79, 0x18, 0x05, 0x20, 0x01, 0x28, 0x01, 0x52, 0x08, 0x6f, 0x74, 0x68, 0x65, 0x72, 0x50,
	0x61, 0x79, 0x12, 0x25, 0x0a, 0x0e, 0x72, 0x65, 0x73, 0x74, 0x61, 0x75, 0x72, 0x61, 0x6e, 0x74,
	0x5f, 0x70, 0x61, 0x79, 0x18, 0x06, 0x20, 0x01, 0x28, 0x01, 0x52, 0x0d, 0x72, 0x65, 0x73, 0x74,
	0x61, 0x75, 0x72, 0x61, 0x6e, 0x74, 0x50, 0x61, 0x79, 0x12, 0x1f, 0x0a, 0x0b, 0x6c, 0x69, 0x62,
	0x72, 0x61, 0x72, 0x79, 0x5f, 0x70, 0x61, 0x79, 0x18, 0x08, 0x20, 0x01, 0x28, 0x01, 0x52, 0x0a,
	0x6c, 0x69, 0x62, 0x72, 0x61, 0x72, 0x79, 0x50, 0x61, 0x79, 0x22, 0x50, 0x0a, 0x13, 0x42, 0x6f,
	0x6f, 0x6b, 0x44, 0x61, 0x74, 0x61, 0x49, 0x6e, 0x69, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x17, 0x0a, 0x07, 0x73, 0x74, 0x75, 0x5f, 0x6e, 0x75, 0x6d, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x75, 0x4e, 0x75, 0x6d, 0x12, 0x20, 0x0a, 0x0b, 0x6a, 0x73,
	0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0b, 0x6a, 0x73, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x69, 0x64, 0x22, 0x2a, 0x0a, 0x14,
	0x42, 0x6f, 0x6f, 0x6b, 0x44, 0x61, 0x74, 0x61, 0x49, 0x6e, 0x69, 0x74, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x66, 0x6c, 0x61, 0x67, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x04, 0x66, 0x6c, 0x61, 0x67, 0x22, 0x70, 0x0a, 0x14, 0x4c, 0x65, 0x61, 0x72,
	0x6e, 0x44, 0x61, 0x74, 0x61, 0x49, 0x6e, 0x69, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x17, 0x0a, 0x07, 0x73, 0x74, 0x75, 0x5f, 0x6e, 0x75, 0x6d, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x73, 0x74, 0x75, 0x4e, 0x75, 0x6d, 0x12, 0x1c, 0x0a, 0x09, 0x67, 0x73, 0x53,
	0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x67, 0x73,
	0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x21, 0x0a, 0x0c, 0x65, 0x6d, 0x61, 0x70, 0x68,
	0x6f, 0x6d, 0x65, 0x5f, 0x57, 0x45, 0x55, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x65,
	0x6d, 0x61, 0x70, 0x68, 0x6f, 0x6d, 0x65, 0x57, 0x45, 0x55, 0x22, 0xa7, 0x01, 0x0a, 0x15, 0x4c,
	0x65, 0x61, 0x72, 0x6e, 0x44, 0x61, 0x74, 0x61, 0x49, 0x6e, 0x69, 0x74, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x6d, 0x6f, 0x73, 0x74, 0x5f, 0x63, 0x6f, 0x75,
	0x72, 0x73, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x6d, 0x6f, 0x73, 0x74, 0x43,
	0x6f, 0x75, 0x72, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x65, 0x69, 0x67, 0x68, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x74,
	0x65, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x74, 0x65, 0x6e, 0x12, 0x1d, 0x0a,
	0x0a, 0x73, 0x75, 0x6d, 0x5f, 0x6c, 0x65, 0x73, 0x73, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x09, 0x73, 0x75, 0x6d, 0x4c, 0x65, 0x73, 0x73, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04,
	0x6d, 0x6f, 0x73, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x6d, 0x6f, 0x73, 0x74,
	0x12, 0x12, 0x0a, 0x04, 0x66, 0x6c, 0x61, 0x67, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04,
	0x66, 0x6c, 0x61, 0x67, 0x22, 0x95, 0x01, 0x0a, 0x12, 0x44, 0x61, 0x74, 0x61, 0x53, 0x74, 0x6f,
	0x72, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x73,
	0x74, 0x75, 0x5f, 0x6e, 0x75, 0x6d, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74,
	0x75, 0x4e, 0x75, 0x6d, 0x12, 0x35, 0x0a, 0x0a, 0x6c, 0x65, 0x61, 0x72, 0x6e, 0x5f, 0x64, 0x61,
	0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x4c, 0x65, 0x61, 0x72, 0x6e,
	0x44, 0x61, 0x74, 0x61, 0x49, 0x6e, 0x69, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x52, 0x09, 0x6c, 0x65, 0x61, 0x72, 0x6e, 0x44, 0x61, 0x74, 0x61, 0x12, 0x2f, 0x0a, 0x08, 0x70,
	0x61, 0x79, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e,
	0x50, 0x61, 0x79, 0x44, 0x61, 0x74, 0x61, 0x49, 0x6e, 0x69, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x52, 0x07, 0x70, 0x61, 0x79, 0x44, 0x61, 0x74, 0x61, 0x22, 0x6f, 0x0a, 0x13,
	0x47, 0x65, 0x74, 0x42, 0x6f, 0x6f, 0x6b, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x72, 0x65, 0x61, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x04, 0x72, 0x65, 0x61, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x72, 0x65, 0x61, 0x64, 0x69,
	0x6e, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x72, 0x65, 0x61, 0x64, 0x69, 0x6e,
	0x67, 0x12, 0x18, 0x0a, 0x07, 0x6c, 0x6f, 0x6e, 0x67, 0x65, 0x73, 0x74, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x6c, 0x6f, 0x6e, 0x67, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x64,
	0x61, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x64, 0x61, 0x79, 0x22, 0x2c, 0x0a,
	0x11, 0x47, 0x65, 0x74, 0x50, 0x61, 0x79, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x73, 0x74, 0x75, 0x5f, 0x6e, 0x75, 0x6d, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x75, 0x4e, 0x75, 0x6d, 0x22, 0xd4, 0x02, 0x0a, 0x12,
	0x47, 0x65, 0x74, 0x50, 0x61, 0x79, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x2f, 0x0a, 0x13, 0x66, 0x61, 0x76, 0x6f, 0x72, 0x69, 0x74, 0x65, 0x5f, 0x72,
	0x65, 0x73, 0x74, 0x61, 0x75, 0x72, 0x61, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x12, 0x66, 0x61, 0x76, 0x6f, 0x72, 0x69, 0x74, 0x65, 0x52, 0x65, 0x73, 0x74, 0x61, 0x75, 0x72,
	0x61, 0x6e, 0x74, 0x12, 0x38, 0x0a, 0x09, 0x65, 0x61, 0x72, 0x6c, 0x79, 0x54, 0x69, 0x6d, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x52, 0x09, 0x65, 0x61, 0x72, 0x6c, 0x79, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x36, 0x0a,
	0x08, 0x6c, 0x61, 0x73, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x08, 0x6c, 0x61, 0x73,
	0x74, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x36, 0x0a, 0x17, 0x66, 0x61, 0x76, 0x6f, 0x72, 0x69, 0x74,
	0x65, 0x5f, 0x72, 0x65, 0x73, 0x74, 0x61, 0x75, 0x72, 0x61, 0x6e, 0x74, 0x5f, 0x70, 0x61, 0x79,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x01, 0x52, 0x15, 0x66, 0x61, 0x76, 0x6f, 0x72, 0x69, 0x74, 0x65,
	0x52, 0x65, 0x73, 0x74, 0x61, 0x75, 0x72, 0x61, 0x6e, 0x74, 0x50, 0x61, 0x79, 0x12, 0x1b, 0x0a,
	0x09, 0x6f, 0x74, 0x68, 0x65, 0x72, 0x5f, 0x70, 0x61, 0x79, 0x18, 0x05, 0x20, 0x01, 0x28, 0x01,
	0x52, 0x08, 0x6f, 0x74, 0x68, 0x65, 0x72, 0x50, 0x61, 0x79, 0x12, 0x25, 0x0a, 0x0e, 0x72, 0x65,
	0x73, 0x74, 0x61, 0x75, 0x72, 0x61, 0x6e, 0x74, 0x5f, 0x70, 0x61, 0x79, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x01, 0x52, 0x0d, 0x72, 0x65, 0x73, 0x74, 0x61, 0x75, 0x72, 0x61, 0x6e, 0x74, 0x50, 0x61,
	0x79, 0x12, 0x1f, 0x0a, 0x0b, 0x6c, 0x69, 0x62, 0x72, 0x61, 0x72, 0x79, 0x5f, 0x70, 0x61, 0x79,
	0x18, 0x07, 0x20, 0x01, 0x28, 0x01, 0x52, 0x0a, 0x6c, 0x69, 0x62, 0x72, 0x61, 0x72, 0x79, 0x50,
	0x61, 0x79, 0x22, 0x2e, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x4c, 0x65, 0x61, 0x72, 0x6e, 0x44, 0x61,
	0x74, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x73, 0x74, 0x75,
	0x5f, 0x6e, 0x75, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x75, 0x4e,
	0x75, 0x6d, 0x22, 0x92, 0x01, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x4c, 0x65, 0x61, 0x72, 0x6e, 0x44,
	0x61, 0x74, 0x61, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x6d,
	0x6f, 0x73, 0x74, 0x5f, 0x63, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0a, 0x6d, 0x6f, 0x73, 0x74, 0x43, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04,
	0x6d, 0x6f, 0x73, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x6d, 0x6f, 0x73, 0x74,
	0x12, 0x14, 0x0a, 0x05, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x05, 0x65, 0x69, 0x67, 0x68, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x74, 0x65, 0x6e, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x03, 0x74, 0x65, 0x6e, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x75, 0x6d, 0x5f,
	0x6c, 0x65, 0x73, 0x73, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x73, 0x75,
	0x6d, 0x4c, 0x65, 0x73, 0x73, 0x6f, 0x6e, 0x22, 0x29, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x52, 0x61,
	0x6e, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x73, 0x74, 0x75,
	0x5f, 0x6e, 0x75, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x75, 0x4e,
	0x75, 0x6d, 0x22, 0x5b, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x52, 0x61, 0x6e, 0x6b, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x1c, 0x0a, 0x09, 0x61,
	0x70, 0x70, 0x72, 0x61, 0x69, 0x73, 0x61, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09,
	0x61, 0x70, 0x70, 0x72, 0x61, 0x69, 0x73, 0x61, 0x6c, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x22,
	0x48, 0x0a, 0x0f, 0x41, 0x70, 0x70, 0x72, 0x61, 0x69, 0x73, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x73, 0x74, 0x75, 0x5f, 0x6e, 0x75, 0x6d, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x75, 0x4e, 0x75, 0x6d, 0x12, 0x1c, 0x0a, 0x09, 0x61,
	0x70, 0x70, 0x72, 0x61, 0x69, 0x73, 0x61, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09,
	0x61, 0x70, 0x70, 0x72, 0x61, 0x69, 0x73, 0x61, 0x6c, 0x22, 0x2c, 0x0a, 0x11, 0x43, 0x68, 0x65,
	0x63, 0x6b, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17,
	0x0a, 0x07, 0x73, 0x74, 0x75, 0x5f, 0x6e, 0x75, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x73, 0x74, 0x75, 0x4e, 0x75, 0x6d, 0x22, 0x2a, 0x0a, 0x12, 0x43, 0x68, 0x65, 0x63, 0x6b,
	0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a,
	0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x73, 0x74,
	0x61, 0x74, 0x65, 0x32, 0xce, 0x04, 0x0a, 0x0f, 0x59, 0x65, 0x61, 0x72, 0x42, 0x69, 0x6c, 0x6c,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x32, 0x0a, 0x09, 0x49, 0x6e, 0x66, 0x6f, 0x43,
	0x68, 0x65, 0x63, 0x6b, 0x12, 0x11, 0x2e, 0x49, 0x6e, 0x66, 0x6f, 0x43, 0x68, 0x65, 0x63, 0x6b,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x12, 0x2e, 0x49, 0x6e, 0x66, 0x6f, 0x43, 0x68,
	0x65, 0x63, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x41, 0x0a, 0x0e, 0x47,
	0x65, 0x74, 0x43, 0x65, 0x72, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x65, 0x12, 0x16, 0x2e,
	0x47, 0x65, 0x74, 0x43, 0x65, 0x72, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x47, 0x65, 0x74, 0x43, 0x65, 0x72, 0x74, 0x69,
	0x66, 0x69, 0x63, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3d,
	0x0a, 0x0c, 0x59, 0x65, 0x61, 0x72, 0x42, 0x69, 0x6c, 0x6c, 0x50, 0x69, 0x6e, 0x67, 0x12, 0x16,
	0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x15, 0x2e, 0x59, 0x65, 0x61, 0x72, 0x42, 0x69, 0x6c,
	0x6c, 0x50, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x35, 0x0a,
	0x0a, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x12, 0x2e, 0x43, 0x68,
	0x65, 0x63, 0x6b, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x13, 0x2e, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x34, 0x0a, 0x08, 0x41, 0x70, 0x70, 0x72, 0x61, 0x69, 0x73, 0x65,
	0x12, 0x10, 0x2e, 0x41, 0x70, 0x70, 0x72, 0x61, 0x69, 0x73, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x12, 0x3a, 0x0a, 0x0b, 0x44, 0x61,
	0x74, 0x61, 0x53, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x12, 0x13, 0x2e, 0x44, 0x61, 0x74, 0x61,
	0x53, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16,
	0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x12, 0x3b, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x4c, 0x65, 0x61,
	0x72, 0x6e, 0x44, 0x61, 0x74, 0x61, 0x12, 0x14, 0x2e, 0x47, 0x65, 0x74, 0x4c, 0x65, 0x61, 0x72,
	0x6e, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e, 0x47,
	0x65, 0x74, 0x4c, 0x65, 0x61, 0x72, 0x6e, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x35, 0x0a, 0x0a, 0x47, 0x65, 0x74, 0x50, 0x61, 0x79, 0x44, 0x61, 0x74,
	0x61, 0x12, 0x12, 0x2e, 0x47, 0x65, 0x74, 0x50, 0x61, 0x79, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x13, 0x2e, 0x47, 0x65, 0x74, 0x50, 0x61, 0x79, 0x44, 0x61,
	0x74, 0x61, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3a, 0x0a, 0x08, 0x44, 0x61,
	0x74, 0x61, 0x49, 0x6e, 0x69, 0x74, 0x12, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x16,
	0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x12, 0x2c, 0x0a, 0x07, 0x47, 0x65, 0x74, 0x52, 0x61, 0x6e,
	0x6b, 0x12, 0x0f, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x61, 0x6e, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x10, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x61, 0x6e, 0x6b, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x42, 0x0b, 0x5a, 0x09, 0x79, 0x65, 0x61, 0x72, 0x42, 0x69, 0x6c, 0x6c,
	0x2f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_yearBill_proto_rawDescOnce sync.Once
	file_yearBill_proto_rawDescData = file_yearBill_proto_rawDesc
)

func file_yearBill_proto_rawDescGZIP() []byte {
	file_yearBill_proto_rawDescOnce.Do(func() {
		file_yearBill_proto_rawDescData = protoimpl.X.CompressGZIP(file_yearBill_proto_rawDescData)
	})
	return file_yearBill_proto_rawDescData
}

var file_yearBill_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_yearBill_proto_goTypes = []interface{}{
	(*YearBillPingResponse)(nil),   // 0: YearBillPingResponse
	(*InfoCheckRequest)(nil),       // 1: InfoCheckRequest
	(*InfoCheckResponse)(nil),      // 2: InfoCheckResponse
	(*GetCertificateRequest)(nil),  // 3: GetCertificateRequest
	(*GetCertificateResponse)(nil), // 4: GetCertificateResponse
	(*DataInitRequest)(nil),        // 5: DataInitRequest
	(*PayDataInitRequest)(nil),     // 6: PayDataInitRequest
	(*PayDataInitResponse)(nil),    // 7: PayDataInitResponse
	(*BookDataInitRequest)(nil),    // 8: BookDataInitRequest
	(*BookDataInitResponse)(nil),   // 9: BookDataInitResponse
	(*LearnDataInitRequest)(nil),   // 10: LearnDataInitRequest
	(*LearnDataInitResponse)(nil),  // 11: LearnDataInitResponse
	(*DataStorageRequest)(nil),     // 12: DataStorageRequest
	(*GetBookDataResponse)(nil),    // 13: GetBookDataResponse
	(*GetPayDataRequest)(nil),      // 14: GetPayDataRequest
	(*GetPayDataResponse)(nil),     // 15: GetPayDataResponse
	(*GetLearnDataRequest)(nil),    // 16: GetLearnDataRequest
	(*GetLearnDataResponse)(nil),   // 17: GetLearnDataResponse
	(*GetRankRequest)(nil),         // 18: GetRankRequest
	(*GetRankResponse)(nil),        // 19: GetRankResponse
	(*AppraiseRequest)(nil),        // 20: AppraiseRequest
	(*CheckStateRequest)(nil),      // 21: CheckStateRequest
	(*CheckStateResponse)(nil),     // 22: CheckStateResponse
	(*timestamppb.Timestamp)(nil),  // 23: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),          // 24: google.protobuf.Empty
}
var file_yearBill_proto_depIdxs = []int32{
	23, // 0: PayDataInitResponse.earlyTime:type_name -> google.protobuf.Timestamp
	23, // 1: PayDataInitResponse.lastTime:type_name -> google.protobuf.Timestamp
	11, // 2: DataStorageRequest.learn_data:type_name -> LearnDataInitResponse
	7,  // 3: DataStorageRequest.pay_data:type_name -> PayDataInitResponse
	23, // 4: GetPayDataResponse.earlyTime:type_name -> google.protobuf.Timestamp
	23, // 5: GetPayDataResponse.lastTime:type_name -> google.protobuf.Timestamp
	1,  // 6: YearBillService.InfoCheck:input_type -> InfoCheckRequest
	3,  // 7: YearBillService.GetCertificate:input_type -> GetCertificateRequest
	24, // 8: YearBillService.YearBillPing:input_type -> google.protobuf.Empty
	21, // 9: YearBillService.CheckState:input_type -> CheckStateRequest
	20, // 10: YearBillService.Appraise:input_type -> AppraiseRequest
	12, // 11: YearBillService.DataStorage:input_type -> DataStorageRequest
	16, // 12: YearBillService.GetLearnData:input_type -> GetLearnDataRequest
	14, // 13: YearBillService.GetPayData:input_type -> GetPayDataRequest
	24, // 14: YearBillService.DataInit:input_type -> google.protobuf.Empty
	18, // 15: YearBillService.GetRank:input_type -> GetRankRequest
	2,  // 16: YearBillService.InfoCheck:output_type -> InfoCheckResponse
	4,  // 17: YearBillService.GetCertificate:output_type -> GetCertificateResponse
	0,  // 18: YearBillService.YearBillPing:output_type -> YearBillPingResponse
	22, // 19: YearBillService.CheckState:output_type -> CheckStateResponse
	24, // 20: YearBillService.Appraise:output_type -> google.protobuf.Empty
	24, // 21: YearBillService.DataStorage:output_type -> google.protobuf.Empty
	17, // 22: YearBillService.GetLearnData:output_type -> GetLearnDataResponse
	15, // 23: YearBillService.GetPayData:output_type -> GetPayDataResponse
	24, // 24: YearBillService.DataInit:output_type -> google.protobuf.Empty
	19, // 25: YearBillService.GetRank:output_type -> GetRankResponse
	16, // [16:26] is the sub-list for method output_type
	6,  // [6:16] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_yearBill_proto_init() }
func file_yearBill_proto_init() {
	if File_yearBill_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_yearBill_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*YearBillPingResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_yearBill_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InfoCheckRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_yearBill_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InfoCheckResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_yearBill_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetCertificateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_yearBill_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetCertificateResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_yearBill_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DataInitRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_yearBill_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PayDataInitRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_yearBill_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PayDataInitResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_yearBill_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BookDataInitRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_yearBill_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BookDataInitResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_yearBill_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LearnDataInitRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_yearBill_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LearnDataInitResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_yearBill_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DataStorageRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_yearBill_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetBookDataResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_yearBill_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPayDataRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_yearBill_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPayDataResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_yearBill_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetLearnDataRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_yearBill_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetLearnDataResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_yearBill_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetRankRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_yearBill_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetRankResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_yearBill_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AppraiseRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_yearBill_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckStateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_yearBill_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckStateResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_yearBill_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_yearBill_proto_goTypes,
		DependencyIndexes: file_yearBill_proto_depIdxs,
		MessageInfos:      file_yearBill_proto_msgTypes,
	}.Build()
	File_yearBill_proto = out.File
	file_yearBill_proto_rawDesc = nil
	file_yearBill_proto_goTypes = nil
	file_yearBill_proto_depIdxs = nil
}
