// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v4.23.2
// source: school.proto

package school

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SchoolPingResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *SchoolPingResponse) Reset() {
	*x = SchoolPingResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_school_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SchoolPingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SchoolPingResponse) ProtoMessage() {}

func (x *SchoolPingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_school_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SchoolPingResponse.ProtoReflect.Descriptor instead.
func (*SchoolPingResponse) Descriptor() ([]byte, []int) {
	return file_school_proto_rawDescGZIP(), []int{0}
}

func (x *SchoolPingResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type Gpa struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Semester  string `protobuf:"bytes,1,opt,name=Semester,proto3" json:"Semester,omitempty"`
	Gpa       string `protobuf:"bytes,2,opt,name=Gpa,proto3" json:"Gpa,omitempty"`
	ClassRank string `protobuf:"bytes,3,opt,name=ClassRank,proto3" json:"ClassRank,omitempty"`
	MajorRank string `protobuf:"bytes,4,opt,name=MajorRank,proto3" json:"MajorRank,omitempty"`
}

func (x *Gpa) Reset() {
	*x = Gpa{}
	if protoimpl.UnsafeEnabled {
		mi := &file_school_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Gpa) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Gpa) ProtoMessage() {}

func (x *Gpa) ProtoReflect() protoreflect.Message {
	mi := &file_school_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Gpa.ProtoReflect.Descriptor instead.
func (*Gpa) Descriptor() ([]byte, []int) {
	return file_school_proto_rawDescGZIP(), []int{1}
}

func (x *Gpa) GetSemester() string {
	if x != nil {
		return x.Semester
	}
	return ""
}

func (x *Gpa) GetGpa() string {
	if x != nil {
		return x.Gpa
	}
	return ""
}

func (x *Gpa) GetClassRank() string {
	if x != nil {
		return x.ClassRank
	}
	return ""
}

func (x *Gpa) GetMajorRank() string {
	if x != nil {
		return x.MajorRank
	}
	return ""
}

type SchoolGpaResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Gpa []*Gpa `protobuf:"bytes,1,rep,name=gpa,proto3" json:"gpa,omitempty"`
}

func (x *SchoolGpaResponse) Reset() {
	*x = SchoolGpaResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_school_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SchoolGpaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SchoolGpaResponse) ProtoMessage() {}

func (x *SchoolGpaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_school_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SchoolGpaResponse.ProtoReflect.Descriptor instead.
func (*SchoolGpaResponse) Descriptor() ([]byte, []int) {
	return file_school_proto_rawDescGZIP(), []int{2}
}

func (x *SchoolGpaResponse) GetGpa() []*Gpa {
	if x != nil {
		return x.Gpa
	}
	return nil
}

type Schedule struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TeachWeek   string `protobuf:"bytes,1,opt,name=teachWeek,proto3" json:"teachWeek,omitempty"`
	LessonName  string `protobuf:"bytes,2,opt,name=lessonName,proto3" json:"lessonName,omitempty"`
	Week        string `protobuf:"bytes,3,opt,name=week,proto3" json:"week,omitempty"`
	BeginTime   string `protobuf:"bytes,4,opt,name=beginTime,proto3" json:"beginTime,omitempty"`
	EndTime     string `protobuf:"bytes,5,opt,name=endTime,proto3" json:"endTime,omitempty"`
	Address     string `protobuf:"bytes,6,opt,name=address,proto3" json:"address,omitempty"`
	TeacherName string `protobuf:"bytes,7,opt,name=teacherName,proto3" json:"teacherName,omitempty"`
}

func (x *Schedule) Reset() {
	*x = Schedule{}
	if protoimpl.UnsafeEnabled {
		mi := &file_school_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Schedule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Schedule) ProtoMessage() {}

func (x *Schedule) ProtoReflect() protoreflect.Message {
	mi := &file_school_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Schedule.ProtoReflect.Descriptor instead.
func (*Schedule) Descriptor() ([]byte, []int) {
	return file_school_proto_rawDescGZIP(), []int{3}
}

func (x *Schedule) GetTeachWeek() string {
	if x != nil {
		return x.TeachWeek
	}
	return ""
}

func (x *Schedule) GetLessonName() string {
	if x != nil {
		return x.LessonName
	}
	return ""
}

func (x *Schedule) GetWeek() string {
	if x != nil {
		return x.Week
	}
	return ""
}

func (x *Schedule) GetBeginTime() string {
	if x != nil {
		return x.BeginTime
	}
	return ""
}

func (x *Schedule) GetEndTime() string {
	if x != nil {
		return x.EndTime
	}
	return ""
}

func (x *Schedule) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Schedule) GetTeacherName() string {
	if x != nil {
		return x.TeacherName
	}
	return ""
}

type SchoolScheduleResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Schedules []*Schedule `protobuf:"bytes,1,rep,name=schedules,proto3" json:"schedules,omitempty"`
}

func (x *SchoolScheduleResponse) Reset() {
	*x = SchoolScheduleResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_school_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SchoolScheduleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SchoolScheduleResponse) ProtoMessage() {}

func (x *SchoolScheduleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_school_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SchoolScheduleResponse.ProtoReflect.Descriptor instead.
func (*SchoolScheduleResponse) Descriptor() ([]byte, []int) {
	return file_school_proto_rawDescGZIP(), []int{4}
}

func (x *SchoolScheduleResponse) GetSchedules() []*Schedule {
	if x != nil {
		return x.Schedules
	}
	return nil
}

type Grade struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	XNXQDM  string  `protobuf:"bytes,7,opt,name=XNXQDM,proto3" json:"XNXQDM,omitempty"`
	XSKCM   string  `protobuf:"bytes,1,opt,name=XSKCM,proto3" json:"XSKCM,omitempty"`
	ZCJ     float64 `protobuf:"fixed64,2,opt,name=ZCJ,proto3" json:"ZCJ,omitempty"`
	XSZCJMC string  `protobuf:"bytes,3,opt,name=XSZCJMC,proto3" json:"XSZCJMC,omitempty"`
	XF      float64 `protobuf:"fixed64,4,opt,name=XF,proto3" json:"XF,omitempty"`
	QMCJ    string  `protobuf:"bytes,5,opt,name=QMCJ,proto3" json:"QMCJ,omitempty"`
	PSCJ    string  `protobuf:"bytes,6,opt,name=PSCJ,proto3" json:"PSCJ,omitempty"`
}

func (x *Grade) Reset() {
	*x = Grade{}
	if protoimpl.UnsafeEnabled {
		mi := &file_school_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Grade) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Grade) ProtoMessage() {}

func (x *Grade) ProtoReflect() protoreflect.Message {
	mi := &file_school_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Grade.ProtoReflect.Descriptor instead.
func (*Grade) Descriptor() ([]byte, []int) {
	return file_school_proto_rawDescGZIP(), []int{5}
}

func (x *Grade) GetXNXQDM() string {
	if x != nil {
		return x.XNXQDM
	}
	return ""
}

func (x *Grade) GetXSKCM() string {
	if x != nil {
		return x.XSKCM
	}
	return ""
}

func (x *Grade) GetZCJ() float64 {
	if x != nil {
		return x.ZCJ
	}
	return 0
}

func (x *Grade) GetXSZCJMC() string {
	if x != nil {
		return x.XSZCJMC
	}
	return ""
}

func (x *Grade) GetXF() float64 {
	if x != nil {
		return x.XF
	}
	return 0
}

func (x *Grade) GetQMCJ() string {
	if x != nil {
		return x.QMCJ
	}
	return ""
}

func (x *Grade) GetPSCJ() string {
	if x != nil {
		return x.PSCJ
	}
	return ""
}

type SchoolGradeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Grade []*Grade `protobuf:"bytes,1,rep,name=grade,proto3" json:"grade,omitempty"`
}

func (x *SchoolGradeResponse) Reset() {
	*x = SchoolGradeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_school_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SchoolGradeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SchoolGradeResponse) ProtoMessage() {}

func (x *SchoolGradeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_school_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SchoolGradeResponse.ProtoReflect.Descriptor instead.
func (*SchoolGradeResponse) Descriptor() ([]byte, []int) {
	return file_school_proto_rawDescGZIP(), []int{6}
}

func (x *SchoolGradeResponse) GetGrade() []*Grade {
	if x != nil {
		return x.Grade
	}
	return nil
}

type Xytj struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	XNXQDM string  `protobuf:"bytes,1,opt,name=XNXQDM,proto3" json:"XNXQDM,omitempty"`
	YXXF   float64 `protobuf:"fixed64,2,opt,name=YXXF,proto3" json:"YXXF,omitempty"`
	YHXF   float64 `protobuf:"fixed64,3,opt,name=YHXF,proto3" json:"YHXF,omitempty"`
	BJGXF  float64 `protobuf:"fixed64,4,opt,name=BJGXF,proto3" json:"BJGXF,omitempty"`
	WLCJXF float64 `protobuf:"fixed64,5,opt,name=WLCJXF,proto3" json:"WLCJXF,omitempty"`
}

func (x *Xytj) Reset() {
	*x = Xytj{}
	if protoimpl.UnsafeEnabled {
		mi := &file_school_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Xytj) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Xytj) ProtoMessage() {}

func (x *Xytj) ProtoReflect() protoreflect.Message {
	mi := &file_school_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Xytj.ProtoReflect.Descriptor instead.
func (*Xytj) Descriptor() ([]byte, []int) {
	return file_school_proto_rawDescGZIP(), []int{7}
}

func (x *Xytj) GetXNXQDM() string {
	if x != nil {
		return x.XNXQDM
	}
	return ""
}

func (x *Xytj) GetYXXF() float64 {
	if x != nil {
		return x.YXXF
	}
	return 0
}

func (x *Xytj) GetYHXF() float64 {
	if x != nil {
		return x.YHXF
	}
	return 0
}

func (x *Xytj) GetBJGXF() float64 {
	if x != nil {
		return x.BJGXF
	}
	return 0
}

func (x *Xytj) GetWLCJXF() float64 {
	if x != nil {
		return x.WLCJXF
	}
	return 0
}

type SchoolXuefenResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Xuefen []*Xytj `protobuf:"bytes,1,rep,name=xuefen,proto3" json:"xuefen,omitempty"`
}

func (x *SchoolXuefenResponse) Reset() {
	*x = SchoolXuefenResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_school_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SchoolXuefenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SchoolXuefenResponse) ProtoMessage() {}

func (x *SchoolXuefenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_school_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SchoolXuefenResponse.ProtoReflect.Descriptor instead.
func (*SchoolXuefenResponse) Descriptor() ([]byte, []int) {
	return file_school_proto_rawDescGZIP(), []int{8}
}

func (x *SchoolXuefenResponse) GetXuefen() []*Xytj {
	if x != nil {
		return x.Xuefen
	}
	return nil
}

var File_school_proto protoreflect.FileDescriptor

var file_school_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x73, 0x63, 0x68, 0x6f, 0x6f, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1b,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f,
	0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x2e, 0x0a, 0x12, 0x53,
	0x63, 0x68, 0x6f, 0x6f, 0x6c, 0x50, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x6f, 0x0a, 0x03, 0x47,
	0x70, 0x61, 0x12, 0x1a, 0x0a, 0x08, 0x53, 0x65, 0x6d, 0x65, 0x73, 0x74, 0x65, 0x72, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x53, 0x65, 0x6d, 0x65, 0x73, 0x74, 0x65, 0x72, 0x12, 0x10,
	0x0a, 0x03, 0x47, 0x70, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x47, 0x70, 0x61,
	0x12, 0x1c, 0x0a, 0x09, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x52, 0x61, 0x6e, 0x6b, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x52, 0x61, 0x6e, 0x6b, 0x12, 0x1c,
	0x0a, 0x09, 0x4d, 0x61, 0x6a, 0x6f, 0x72, 0x52, 0x61, 0x6e, 0x6b, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x4d, 0x61, 0x6a, 0x6f, 0x72, 0x52, 0x61, 0x6e, 0x6b, 0x22, 0x2b, 0x0a, 0x11,
	0x53, 0x63, 0x68, 0x6f, 0x6f, 0x6c, 0x47, 0x70, 0x61, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x16, 0x0a, 0x03, 0x67, 0x70, 0x61, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x04,
	0x2e, 0x47, 0x70, 0x61, 0x52, 0x03, 0x67, 0x70, 0x61, 0x22, 0xd0, 0x01, 0x0a, 0x08, 0x53, 0x63,
	0x68, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x65, 0x61, 0x63, 0x68, 0x57,
	0x65, 0x65, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x74, 0x65, 0x61, 0x63, 0x68,
	0x57, 0x65, 0x65, 0x6b, 0x12, 0x1e, 0x0a, 0x0a, 0x6c, 0x65, 0x73, 0x73, 0x6f, 0x6e, 0x4e, 0x61,
	0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x6c, 0x65, 0x73, 0x73, 0x6f, 0x6e,
	0x4e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x77, 0x65, 0x65, 0x6b, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x77, 0x65, 0x65, 0x6b, 0x12, 0x1c, 0x0a, 0x09, 0x62, 0x65, 0x67, 0x69,
	0x6e, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x62, 0x65, 0x67,
	0x69, 0x6e, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x65, 0x6e, 0x64, 0x54, 0x69, 0x6d,
	0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x65, 0x6e, 0x64, 0x54, 0x69, 0x6d, 0x65,
	0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x20, 0x0a, 0x0b, 0x74, 0x65,
	0x61, 0x63, 0x68, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0b, 0x74, 0x65, 0x61, 0x63, 0x68, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x41, 0x0a, 0x16,
	0x53, 0x63, 0x68, 0x6f, 0x6f, 0x6c, 0x53, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x27, 0x0a, 0x09, 0x73, 0x63, 0x68, 0x65, 0x64, 0x75,
	0x6c, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x53, 0x63, 0x68, 0x65,
	0x64, 0x75, 0x6c, 0x65, 0x52, 0x09, 0x73, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x73, 0x22,
	0x99, 0x01, 0x0a, 0x05, 0x47, 0x72, 0x61, 0x64, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x58, 0x4e, 0x58,
	0x51, 0x44, 0x4d, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x58, 0x4e, 0x58, 0x51, 0x44,
	0x4d, 0x12, 0x14, 0x0a, 0x05, 0x58, 0x53, 0x4b, 0x43, 0x4d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x58, 0x53, 0x4b, 0x43, 0x4d, 0x12, 0x10, 0x0a, 0x03, 0x5a, 0x43, 0x4a, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x01, 0x52, 0x03, 0x5a, 0x43, 0x4a, 0x12, 0x18, 0x0a, 0x07, 0x58, 0x53, 0x5a,
	0x43, 0x4a, 0x4d, 0x43, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x58, 0x53, 0x5a, 0x43,
	0x4a, 0x4d, 0x43, 0x12, 0x0e, 0x0a, 0x02, 0x58, 0x46, 0x18, 0x04, 0x20, 0x01, 0x28, 0x01, 0x52,
	0x02, 0x58, 0x46, 0x12, 0x12, 0x0a, 0x04, 0x51, 0x4d, 0x43, 0x4a, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x51, 0x4d, 0x43, 0x4a, 0x12, 0x12, 0x0a, 0x04, 0x50, 0x53, 0x43, 0x4a, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x50, 0x53, 0x43, 0x4a, 0x22, 0x33, 0x0a, 0x13, 0x53,
	0x63, 0x68, 0x6f, 0x6f, 0x6c, 0x47, 0x72, 0x61, 0x64, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x1c, 0x0a, 0x05, 0x67, 0x72, 0x61, 0x64, 0x65, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x06, 0x2e, 0x47, 0x72, 0x61, 0x64, 0x65, 0x52, 0x05, 0x67, 0x72, 0x61, 0x64, 0x65,
	0x22, 0x74, 0x0a, 0x04, 0x58, 0x79, 0x74, 0x6a, 0x12, 0x16, 0x0a, 0x06, 0x58, 0x4e, 0x58, 0x51,
	0x44, 0x4d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x58, 0x4e, 0x58, 0x51, 0x44, 0x4d,
	0x12, 0x12, 0x0a, 0x04, 0x59, 0x58, 0x58, 0x46, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x04,
	0x59, 0x58, 0x58, 0x46, 0x12, 0x12, 0x0a, 0x04, 0x59, 0x48, 0x58, 0x46, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x01, 0x52, 0x04, 0x59, 0x48, 0x58, 0x46, 0x12, 0x14, 0x0a, 0x05, 0x42, 0x4a, 0x47, 0x58,
	0x46, 0x18, 0x04, 0x20, 0x01, 0x28, 0x01, 0x52, 0x05, 0x42, 0x4a, 0x47, 0x58, 0x46, 0x12, 0x16,
	0x0a, 0x06, 0x57, 0x4c, 0x43, 0x4a, 0x58, 0x46, 0x18, 0x05, 0x20, 0x01, 0x28, 0x01, 0x52, 0x06,
	0x57, 0x4c, 0x43, 0x4a, 0x58, 0x46, 0x22, 0x35, 0x0a, 0x14, 0x53, 0x63, 0x68, 0x6f, 0x6f, 0x6c,
	0x58, 0x75, 0x65, 0x66, 0x65, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1d,
	0x0a, 0x06, 0x78, 0x75, 0x65, 0x66, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x05,
	0x2e, 0x58, 0x79, 0x74, 0x6a, 0x52, 0x06, 0x78, 0x75, 0x65, 0x66, 0x65, 0x6e, 0x32, 0xc2, 0x02,
	0x0a, 0x0d, 0x53, 0x63, 0x68, 0x6f, 0x6f, 0x6c, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12,
	0x39, 0x0a, 0x0a, 0x53, 0x63, 0x68, 0x6f, 0x6f, 0x6c, 0x50, 0x69, 0x6e, 0x67, 0x12, 0x16, 0x2e,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e,
	0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x13, 0x2e, 0x53, 0x63, 0x68, 0x6f, 0x6f, 0x6c, 0x50, 0x69,
	0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x37, 0x0a, 0x09, 0x53, 0x63,
	0x68, 0x6f, 0x6f, 0x6c, 0x47, 0x70, 0x61, 0x12, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a,
	0x12, 0x2e, 0x53, 0x63, 0x68, 0x6f, 0x6f, 0x6c, 0x47, 0x70, 0x61, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x41, 0x0a, 0x0e, 0x53, 0x63, 0x68, 0x6f, 0x6f, 0x6c, 0x53, 0x63, 0x68,
	0x65, 0x64, 0x75, 0x6c, 0x65, 0x12, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x17, 0x2e,
	0x53, 0x63, 0x68, 0x6f, 0x6f, 0x6c, 0x53, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3b, 0x0a, 0x0b, 0x53, 0x63, 0x68, 0x6f, 0x6f, 0x6c,
	0x47, 0x72, 0x61, 0x64, 0x65, 0x12, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x14, 0x2e,
	0x53, 0x63, 0x68, 0x6f, 0x6f, 0x6c, 0x47, 0x72, 0x61, 0x64, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x3d, 0x0a, 0x0c, 0x53, 0x63, 0x68, 0x6f, 0x6f, 0x6c, 0x58, 0x75, 0x65,
	0x66, 0x65, 0x6e, 0x12, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x15, 0x2e, 0x53, 0x63,
	0x68, 0x6f, 0x6f, 0x6c, 0x58, 0x75, 0x65, 0x66, 0x65, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x42, 0x09, 0x5a, 0x07, 0x73, 0x63, 0x68, 0x6f, 0x6f, 0x6c, 0x2f, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_school_proto_rawDescOnce sync.Once
	file_school_proto_rawDescData = file_school_proto_rawDesc
)

func file_school_proto_rawDescGZIP() []byte {
	file_school_proto_rawDescOnce.Do(func() {
		file_school_proto_rawDescData = protoimpl.X.CompressGZIP(file_school_proto_rawDescData)
	})
	return file_school_proto_rawDescData
}

var file_school_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_school_proto_goTypes = []interface{}{
	(*SchoolPingResponse)(nil),     // 0: SchoolPingResponse
	(*Gpa)(nil),                    // 1: Gpa
	(*SchoolGpaResponse)(nil),      // 2: SchoolGpaResponse
	(*Schedule)(nil),               // 3: Schedule
	(*SchoolScheduleResponse)(nil), // 4: SchoolScheduleResponse
	(*Grade)(nil),                  // 5: Grade
	(*SchoolGradeResponse)(nil),    // 6: SchoolGradeResponse
	(*Xytj)(nil),                   // 7: Xytj
	(*SchoolXuefenResponse)(nil),   // 8: SchoolXuefenResponse
	(*emptypb.Empty)(nil),          // 9: google.protobuf.Empty
}
var file_school_proto_depIdxs = []int32{
	1, // 0: SchoolGpaResponse.gpa:type_name -> Gpa
	3, // 1: SchoolScheduleResponse.schedules:type_name -> Schedule
	5, // 2: SchoolGradeResponse.grade:type_name -> Grade
	7, // 3: SchoolXuefenResponse.xuefen:type_name -> Xytj
	9, // 4: SchoolService.SchoolPing:input_type -> google.protobuf.Empty
	9, // 5: SchoolService.SchoolGpa:input_type -> google.protobuf.Empty
	9, // 6: SchoolService.SchoolSchedule:input_type -> google.protobuf.Empty
	9, // 7: SchoolService.SchoolGrade:input_type -> google.protobuf.Empty
	9, // 8: SchoolService.SchoolXuefen:input_type -> google.protobuf.Empty
	0, // 9: SchoolService.SchoolPing:output_type -> SchoolPingResponse
	2, // 10: SchoolService.SchoolGpa:output_type -> SchoolGpaResponse
	4, // 11: SchoolService.SchoolSchedule:output_type -> SchoolScheduleResponse
	6, // 12: SchoolService.SchoolGrade:output_type -> SchoolGradeResponse
	8, // 13: SchoolService.SchoolXuefen:output_type -> SchoolXuefenResponse
	9, // [9:14] is the sub-list for method output_type
	4, // [4:9] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_school_proto_init() }
func file_school_proto_init() {
	if File_school_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_school_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SchoolPingResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_school_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Gpa); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_school_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SchoolGpaResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_school_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Schedule); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_school_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SchoolScheduleResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_school_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Grade); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_school_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SchoolGradeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_school_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Xytj); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_school_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SchoolXuefenResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_school_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_school_proto_goTypes,
		DependencyIndexes: file_school_proto_depIdxs,
		MessageInfos:      file_school_proto_msgTypes,
	}.Build()
	File_school_proto = out.File
	file_school_proto_rawDesc = nil
	file_school_proto_goTypes = nil
	file_school_proto_depIdxs = nil
}
